redhat-developer/rhdh-plugins

- CONTRIBUTING.md
- README.md
- workspaces/repo-tools/packages/cli/src/commands/index.ts
- workspaces/repo-tools/packages/cli/src/commands/plugin/janus-migration.ts
- Introduced the command `janus-plugin migrate` to `rhdh-cli` to automate the migration process for Janus plugins.
- Updated the `CONTRIBUTING.md` file with detailed steps on how to use the new migration command.
> added script to migrate janus plugins

- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
The very first AI response is not auto-scrolled due to a check, removed that check in this PR.
>  fix autoscroll issue on first response

- .github/workflows/ci.yml
- workspaces/bulk-import/packages/backend/package.json
- workspaces/bulk-import/yarn.lock
- workspaces/homepage/packages/backend/package.json
- workspaces/homepage/yarn.lock
- workspaces/lightspeed/.changeset/config.json
- workspaces/lightspeed/packages/backend/package.json
- workspaces/lightspeed/yarn.lock
- workspaces/marketplace/packages/backend/package.json
- workspaces/marketplace/yarn.lock
- workspaces/openshift-image-registry/packages/backend/package.json
- workspaces/openshift-image-registry/yarn.lock
- workspaces/theme/packages/backend/package.json
- workspaces/theme/yarn.lock
This PR adds a Verify Changesets step to the ci workflow.
FIxes: https://issues.redhat.com/browse/RHIDP-5033
> chore(ci): add verify changesets step

- .github/workflows/ci.yml
- workspaces/bulk-import/packages/backend/package.json
- workspaces/bulk-import/yarn.lock
- workspaces/homepage/packages/backend/package.json
- workspaces/homepage/yarn.lock
- workspaces/lightspeed/.changeset/config.json
- workspaces/lightspeed/packages/backend/package.json
- workspaces/lightspeed/yarn.lock
- workspaces/marketplace/packages/backend/package.json
- workspaces/marketplace/yarn.lock
- workspaces/openshift-image-registry/packages/backend/package.json
- workspaces/openshift-image-registry/yarn.lock
- workspaces/theme/packages/backend/package.json
- workspaces/theme/yarn.lock
Reverts redhat-developer/rhdh-plugins#65 as there seems to be an issue which is causing the verify changesets step to return an error even when changesets are present.
> Revert "chore(ci): add verify changesets step (#65)"

- workspaces/orchestrator/plugins/orchestrator-form-api/report.api.md
- workspaces/orchestrator/plugins/orchestrator-form-api/src/api.ts
- workspaces/orchestrator/plugins/orchestrator-form-react/src/components/OrchestratorFormWrapper.tsx
backport https://github.com/janus-idp/backstage-plugins/pull/2561
The plugin containing the custom form decorator needs the initial form data to initialize the custom widgets correctly.
This change will enable resolving https://issues.redhat.com/browse/FLPATH-1878
> fix(orchestrator): pass also initial form data to custom decorator

- workspaces/homepage/.changeset/weak-bobcats-taste.md
- workspaces/homepage/plugins/dynamic-home-page/package.json
- workspaces/homepage/yarn.lock
This updates the dynamic-home-page dependencies similar to @kim-tsao PR https://github.com/janus-idp/backstage-showcase/pull/1977, after extracting the code into this repo, and before https://github.com/janus-idp/backstage-showcase/pull/1944 was merged.
> fix(homepage): update dependencies (incl @scalprum/react-core from 0.8 to 0.9)

- workspaces/orchestrator/.changeset/great-students-melt.md
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTable.tsx
- workspaces/orchestrator/plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.test.ts
- workspaces/orchestrator/plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
Due to performance limitations, backend API cannot return the average duration.
This is a follow up on https://github.com/redhat-developer/rhdh-plugins/pull/84/files
> fix(orchestrator): remove average duration from workflow table and overview page

- workspaces/orchestrator/.changeset/polite-chicken-applaud.md
- workspaces/orchestrator/package.json
- workspaces/orchestrator/plugins/orchestrator-common/scripts/openapi.sh
- workspaces/orchestrator/plugins/orchestrator-common/src/generated/docs/api-doc/orchestrator-api.yaml
- workspaces/orchestrator/plugins/orchestrator-common/src/openapi/api-doc-template.yaml
- workspaces/orchestrator/scripts/postinstall
FLPATH-1774
https://issues.redhat.com/browse/FLPATH-1774
> generate openapi spec api-doc

- workspaces/theme/.changeset/wild-squids-sort.md
- workspaces/theme/plugins/theme/package.json
- workspaces/theme/plugins/theme/report.api.md
- workspaces/theme/plugins/theme/src/componentOverrides.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/lightTheme.ts
- workspaces/theme/plugins/theme/src/pageTheme.ts
- workspaces/theme/plugins/theme/src/types.ts
I extracted the initial RHDH theme from https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src/themes/rhdh-1.0
> feat(theme): migrate and release rhdh-theme 0.0.1 (RHDH 1.0)

- workspaces/theme/.changeset/fast-dolphins-act.md
- workspaces/theme/plugins/theme/src/componentOverrides.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/defaultThemePalette.ts
- workspaces/theme/plugins/theme/src/lightTheme.ts
I extracted the initial RHDH theme from https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src/themes/rhdh-1.1
> feat(theme): migrate and release rhdh-theme 0.1.0 (RHDH 1.1)

- workspaces/theme/.changeset/fuzzy-singers-move.md
- workspaces/theme/plugins/theme/package.json
Without this change:
With this change:
> fix(theme): add sideeffect configuration to load Red Hat font from the plugin

- workspaces/theme/.changeset/wild-candles-approve.md
- workspaces/theme/plugins/theme/src/darkTheme.test.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/hooks/useThemeConfig.ts
Apply the 1.3.x RHDH theme changes from @redhat-developer/red-hat-developer-hub-theme@0.3.0.
This will also release also a 0.3.0 version. :)
https://github.com/user-attachments/assets/49314442-460d-4d5b-bcd9-84be879097c9
It shows some theming issues we also have in our main branch, which we didn't had earlier.
These issues are likely related to a Backstage or MUI update?
This PR restores just the old release. I will fix that issue asap after I also applied the current RHDH 1.4 / theme 0.4.
> feat(theme): apply theme changes from RHDH 1.3

- workspaces/theme/.changeset/chilled-countries-divide.md
- workspaces/theme/plugins/mui4-test/src/components/MUI4TestPage.tsx
- workspaces/theme/plugins/mui4-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/mui5-test/src/components/MUI5TestPage.tsx
- workspaces/theme/plugins/mui5-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
> fix(theme): fixed that all disabled elements used a disable background color instead of just disabled tabs

- workspaces/orchestrator/.changeset/cold-phones-raise.md
- workspaces/orchestrator/plugins/orchestrator-swf-editor-envelope/package.json
fix failing release action - https://github.com/redhat-developer/rhdh-plugins/actions/runs/12120055908/job/33787933673
failed since changeset in https://github.com/redhat-developer/rhdh-plugins/pull/95 included a private package @red-hat-developer-hub/backstage-plugin-orchestrator-swf-editor-envelope 
since this PR also included fixing the build, we can make the package public
> chore(orchestrator): fix release action

- workspaces/theme/.changeset/gold-scissors-trade.md
- workspaces/theme/plugins/mui4-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/mui5-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/theme/report.api.md
- workspaces/theme/plugins/theme/src/darkTheme.test.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/lightTheme.test.ts
- workspaces/theme/plugins/theme/src/lightTheme.ts
- workspaces/theme/plugins/theme/src/types.ts
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
Always before and with this PR:
MUI v4 Light theme
MUI v4 Dark theme
MUI v5 Light theme
MUI v4 Dark theme
> fix(theme): align disabled tabs background color more with patternfly (5 for now)

- workspaces/theme/.changeset/moody-camels-design.md
- workspaces/theme/plugins/mui4-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/mui5-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
Removes the border below the vertical tests and the vertical padding (because both aren't there in the backstage theme)
**Main:**
**With this PR:**
> fix(theme): remove bottom border and vertical padding from vertical tabs

- workspaces/theme/.changeset/smooth-berries-cover.md
- workspaces/theme/plugins/mui4-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/mui5-test/src/components/TabExamples.tsx
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
For [RHIDP-5176](https://issues.redhat.com/browse/RHIDP-5176), 
- added hover border bottom for default tabs
- moved indicator to left for vertical tabs, referring PF vertical tabs style
- added a content box for better preview on vertical tabs tests
Before
After
https://github.com/user-attachments/assets/a1a30b20-9413-411b-a755-3ad0332bf1c7
> fix(theme): match tabs style with PF design

- workspaces/theme/.changeset/nasty-needles-smoke.md
- workspaces/theme/.changeset/rare-pears-tap.md
- workspaces/theme/plugins/theme/report.api.md
- workspaces/theme/plugins/theme/src/darkTheme.test.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/lightTheme.test.ts
- workspaces/theme/plugins/theme/src/lightTheme.ts
- workspaces/theme/plugins/theme/src/types.ts
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
#125 focuses on some Paper issues, esp. one padding and the changed background color after components was updated from MUI v4 to v5. #125 contains the first 2 PRs.
But this PR is a more significant visual change because it handles all Paper levels (elevations) same.
1. It **removes the drop shadow from MUI v4** Papers with elevation >= 3 and adds **new borders** to all these 'cards'! The shadow was just removed from elevation 0-2 before.
2. In MUI v5, the drop shadow wasn't displayed for any card, but the border was only there for elevations 1-2.
**The before screenshots incl. #125**
**The before screenshots incl. #125**
> fix(theme): replace the paper shadow and added a border to all paper elevations

- workspaces/theme/.changeset/fresh-jeans-rest.md
- workspaces/theme/plugins/theme/fix-style-inject-imports.sh
- workspaces/theme/plugins/theme/package.json
Fix a `style-inject`(ion) issue with the published package that I noticed in https://github.com/janus-idp/backstage-showcase/pull/2033
See build log: https://github.com/janus-idp/backstage-showcase/actions/runs/12196430482/job/34023993902?pr=2033
An update of `@backstage/cli` with PR https://github.com/backstage/backstage/pull/27547 should also fix this problem, but #141 failed on our CI.
So this adds a workaround similar to https://github.com/backstage/community-plugins/pull/1931.
> fix(theme): add style-inject(ion) issue with the published package

- workspaces/orchestrator/.changeset/empty-plants-dream.md
- workspaces/orchestrator/plugins/orchestrator-backend/__fixtures__/mockComposedGreetingWorfklow.ts
- workspaces/orchestrator/plugins/orchestrator-backend/__fixtures__/mockGreetingWorkflowData.ts
- workspaces/orchestrator/plugins/orchestrator-backend/__fixtures__/mockSpringBootWorkflowData.ts
- workspaces/orchestrator/plugins/orchestrator-backend/package.json
- workspaces/orchestrator/plugins/orchestrator-common/package.json
- workspaces/orchestrator/plugins/orchestrator-form-api/package.json
- workspaces/orchestrator/plugins/orchestrator-form-react/package.json
- workspaces/orchestrator/yarn.lock
orchestrator-common dependencies moved during migration between repos to peerDependencies for some reason. resulting in a broken dynamic-plugin build. The fix moves these packages back to dependencies. The fix also includes cleanup of unneeded dependency on 'json-schema' package as only '@types/json-schema' packages is needed in devDependencies.
> chore(orchestrator): resolve dependencies issue

- workspaces/theme/.changeset/fifty-hotels-joke.md
- workspaces/theme/plugins/theme/report.api.md
- workspaces/theme/plugins/theme/src/darkTheme.test.ts
- workspaces/theme/plugins/theme/src/darkTheme.ts
- workspaces/theme/plugins/theme/src/lightTheme.test.ts
- workspaces/theme/plugins/theme/src/lightTheme.ts
- workspaces/theme/plugins/theme/src/types.ts
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
With recent change #126 we changed all `Paper`s from a box shadow to an outline.
But in a Popover, the Paper component also applies `outline: 0` so that we no border was shown.
This fix adds a box shadow to popovers again because it is more aligned with the [PatternFly 5 Popover](https://v5-archive.patternfly.org/components/popover) than just a border.
**Before:**
Catalog entity action button:
Settings page:
**With this PR:**
Catalog entity action button:
Settings page:
> fix(theme): add missing shadow to action menus/dropdowns that uses the Popover component

- workspaces/orchestrator/plugins/orchestrator/package.json
fix scalprum name following move to new repository, to match name in https://github.com/redhat-developer/rhdh-plugins/blob/fixscalprum/workspaces/orchestrator/plugins/orchestrator/app-config.yaml#L3
> fix(orchestrator): fix scalprum config

- .github/workflows/automate_renovate_changesets.yml
- scripts/ci/generate-bump-changesets.js
Added a workflow to automate renovate changesets based on the one in [community-plugins](https://github.com/backstage/community-plugins/blob/main/.github/workflows/automate_renovate_changesets.yml). 
Took the rhdh bot email from here: https://github.com/redhat-developer/rhdh-chart/blob/a58aa25fa628e6d1d0fd4f27ee44dbbbad502ef8/.github/workflows/bump-version.yml#L117
Took the github.actor based on what is mentioned here: https://github.com/renovatebot/renovate/discussions/13704
> chore: add workflow to automate renovate changesets

- workspaces/marketplace/Makefile
- workspaces/marketplace/app-config.dynamic.yaml
- workspaces/marketplace/packages/app/src/components/Root/Root.tsx
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/package.json
- workspaces/marketplace/plugins/marketplace-backend/package.json
- workspaces/marketplace/plugins/marketplace-common/package.json
- workspaces/marketplace/plugins/marketplace/app-config.dynamic.yaml
- workspaces/marketplace/plugins/marketplace/package.json
- workspaces/marketplace/plugins/marketplace/report.api.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePage.tsx
- workspaces/marketplace/plugins/marketplace/src/index.ts
- workspaces/marketplace/plugins/marketplace/src/plugin.ts
Changes:
1. Export new `MarketplaceIcon` and `MarketplaceCatalogContent` for dynamic plugin usage
2. Add Makefile that allow installation into **local** showcase with one command.  (`make add-to-showcase`, depends on cloned files, see introduction in the Makefile)
3. `app-config.dynamic.yaml` example
* dynamic route works fine
* mounting into plugins page doesn't work (didn't checked why, yet)
4. Change versions to 0.0.0 so that we can maybe (?) release a 0.0.1 soon. :man_shrugging: 
5. Added workaround for MUI v5 so that the self bundled version looks as expected
> feat(marketplace): prepare usage as dynamic plugin (add app-config.dynamic.yaml examples and export icon and content)

- workspaces/bulk-import/yarn.lock
- workspaces/homepage/yarn.lock
- workspaces/lightspeed/yarn.lock
- workspaces/marketplace/yarn.lock
- workspaces/openshift-image-registry/yarn.lock
- workspaces/orchestrator/yarn.lock
- workspaces/repo-tools/yarn.lock
- workspaces/theme/yarn.lock
This is follow-up for updating the yarn to 3.8.7 #192
> chore: Update yarn.lock for yarn 3.8.7

- workspaces/theme/.changeset/warm-grapes-matter.md
- workspaces/theme/plugins/theme/src/components/ThemeProvider.tsx
- workspaces/theme/plugins/theme/src/themes.tsx
> fix(theme): added a workaround so that defaultProps are also picked up from MUI v5 components (like Button disabledRipple or Grid spacing)

- workspaces/theme/.changeset/brave-sloths-cross.md
- workspaces/theme/plugins/theme/package.json
- workspaces/theme/yarn.lock
To be honest, this is more like an experiment. Maybe we can give it a try to check this with a new theme release (which isn't used yet) and rhdh-showcase?
> fix(theme): move the mui v5 package to a peer dependency to ensure that we don't load it twice

- workspaces/theme/.changeset/nine-taxis-beam.md
- workspaces/theme/plugins/theme/CHANGELOG.md
- workspaces/theme/plugins/theme/package.json
Release of #208 failed. From build https://github.com/redhat-developer/rhdh-plugins/actions/runs/12408641051/job/34640814865:
```
➤ YN0000: [@red-hat-developer-hub/backstage-plugin-theme]: ➤ YN0036: Calling the "prepublish" lifecycle script
➤ YN0000: [@red-hat-developer-hub/backstage-plugin-theme]: ➤ YN0000: @red-hat-developer-hub/backstage-plugin-theme@workspace:plugins/theme STDERR command not found: ./fix-style-inject-imports.sh
➤ YN0000: [@red-hat-developer-hub/backstage-plugin-theme]: ➤ YN0036: Prepublish script failed (exit code 127, logs can be found here: /tmp/xfs-bd698101/prepublish.log); run yarn prepublish to investigate
➤ YN0000: [@red-hat-developer-hub/backstage-plugin-theme]: ➤ YN0000: Failed with errors in 0s 979ms
```
This reverts #208 so that we can have a new version PR …
> fix(theme): fix release after fix-style-inject-imports.sh was removed in @202

- workspaces/orchestrator/.changeset/moody-rivers-greet.md
- workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTable.tsx
reslove [FLPATH-1888](https://issues.redhat.com/browse/FLPATH-1888)
right button added - routing to all instances of this specific workflow:
> fix(orchestrator): add runs button

- workspaces/orchestrator/.changeset/wild-owls-invite.md
- workspaces/orchestrator/plugins/orchestrator-common/report.api.md
- workspaces/orchestrator/plugins/orchestrator-common/src/constants.ts
resolves broken developer environment, following sonataflow images moving from docker hub to quay
> chore(orchestrator): update devmode image

- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetail.ts
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/hooks/usePolling.ts
Multiple bug fixes in instances table following https://github.com/redhat-developer/rhdh-plugins/pull/211
1. Each click on sort resulted in two calls to backend, one with previous sort direction and one with new one, resulting in inconsistent results. Fix is by disabling useSwr revalidateOnFocus.
2. Sorting didn't display results in correct order, since material-table overrides the order from backend with simple sort by string. The only way to resolve this was to force the additional sorting to use the same order received from backend.
3. Sort by workflow name failed because it sent to backend the field 'name' instead of 'processName'
4. Sorting was enabled for fields that aren't supported by backend: category and duration
> fix(orchestrator): multiple bug fixes following pagination PR

- workspaces/marketplace/plugins/marketplace/package.json
- workspaces/marketplace/plugins/marketplace/src/api/MarketplaceBackendClient.tsx
- workspaces/marketplace/plugins/marketplace/src/api/MarketplaceCatalogClient.tsx
- workspaces/marketplace/plugins/marketplace/src/api/index.ts
- workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.tsx
- workspaces/marketplace/plugins/marketplace/src/hooks/usePluginList.ts
- workspaces/marketplace/plugins/marketplace/src/hooks/usePlugins.ts
- workspaces/marketplace/plugins/marketplace/src/plugin.ts
- workspaces/marketplace/yarn.lock
https://issues.redhat.com/browse/RHIDP-5321
Changes:
- used catalog API to fetch all the plugins and pluginLists.
-  introduced both the catalog and marketplace backend APIs to easily switch implementations.
- removed redundant type declarations infavor of `Entity`from `@backstage/types`
- `yarn dev` in marketplace workspace, by default it uses MarketplaceBackendClient.
Change `factory` method to use MarketplaceCatalogClient `plugin.ts` 
```
export const marketplacePlugin = createPlugin({
id: 'marketplace',
routes: {
root: rootRouteRef,
},
apis: [
createApiFactory({
api: marketplaceApiRef,
deps: {
catalogApi: catalogApiRef,
},
factory: ({ catalogApi }) =>
new MarketplaceCatalogClient({
catalogApi,
}),
}),
],
});
```
> feat(marketplace): use catalogApi to fetch marketplace plugins

- workspaces/openshift-image-registry/app-config.yaml
I got CORS issues when the OpenShift Image registry plugin fetches information from a included backstage app.
This additional, default backstage configuration solves that problem.
> chore(openshift-image-registry): add missing CORS configuration to test plugin with the bundled backstage app

- workspaces/global-header/packages/app/src/components/Root/Root.tsx
- workspaces/global-header/plugins/global-header/package.json
- workspaces/global-header/plugins/global-header/src/components/ExampleComponent/ExampleComponent.test.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/CreateDropdown.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/HeaderDropdownComponent.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchBar.module.css
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchBar.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchComponent.tsx
- workspaces/global-header/plugins/global-header/src/utils/stringUtils.test.tsx
- workspaces/global-header/plugins/global-header/src/utils/stringUtils.tsx
- workspaces/global-header/yarn.lock
For [RHIDP-5365](https://issues.redhat.com/browse/RHIDP-5365)
screen recording
https://github.com/user-attachments/assets/0f81b568-7bf2-4da9-8110-630f5c3bcd1c
> feat(global-header): implemented searchBar

- workspaces/marketplace/.changeset/slimy-paws-dance.md
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePluginListProcessor.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePluginListProcessor.ts
https://issues.redhat.com/browse/RHIDP-5564
This PR fixes the `Plugin` relationship graph to show its relation with `PluginList` entity.
| Before  |  After |
| ------------- | ------------- |
| ![plugin_relations_missing_pluginlist](https://github.com/user-attachments/assets/1d52efbf-1e19-4b6c-ad95-81b1cfa3574b) | ![plugins_relationship_with_pluginlist](https://github.com/user-attachments/assets/36baa6c8-e409-40a3-bee5-789f745b4691)|
---
> fix(marketplace): emit pluginlist relationships bidirectionally to establish complete connections

- workspaces/global-header/.changeset/fuzzy-sheep-doubt.md
- workspaces/global-header/.changeset/gorgeous-carrots-tie.md
- workspaces/global-header/plugins/global-header-test/package.json
- workspaces/global-header/plugins/global-header-test/src/index.ts
* Add dist-scalprum folder to enable dynamic plugin support for the npm package. This is an interim solution until we have automated container images for all plugins.
* Add a workaround for the test-plugin for MUI v5 components
> fix(global-header): enable dynamic plugin support for global-header-test plugin

- workspaces/global-header/.changeset/heavy-bulldogs-mate.md
- workspaces/global-header/plugins/global-header/dev/index.tsx
- workspaces/global-header/plugins/global-header/report.api.md
- workspaces/global-header/plugins/global-header/src/components/NotificationBanner.tsx
- workspaces/global-header/plugins/global-header/src/index.ts
- workspaces/global-header/plugins/global-header/src/plugin.ts
This adds a new `NotificationBanner` component that could used also as a "header".
It supports some initial styling options:
I like to add more options later.
> feat(global-header): add new notificationbanner component

- catalog-info-teams.yaml
- catalog-info.yaml
- workspaces/bulk-import/catalog-info.yaml
- workspaces/bulk-import/plugins/bulk-import-backend/catalog-info.yaml
- workspaces/bulk-import/plugins/bulk-import-common/catalog-info.yaml
- workspaces/bulk-import/plugins/bulk-import/catalog-info.yaml
- workspaces/global-floating-action-button/catalog-info.yaml
- workspaces/global-header/catalog-info.yaml
- workspaces/homepage/catalog-info.yaml
- workspaces/lightspeed/catalog-info.yaml
- workspaces/marketplace/catalog-info.yaml
- workspaces/openshift-image-registry/catalog-info.yaml
- workspaces/openshift-image-registry/plugins/openshift-image-registry/catalog-info.yaml
- workspaces/orchestrator/catalog-info.yaml
- workspaces/orchestrator/plugins/orchestrator-backend/catalog-info.yaml
- workspaces/orchestrator/plugins/orchestrator-common/catalog-info.yaml
- workspaces/orchestrator/plugins/orchestrator-swf-editor-envelope/catalog-info.yaml
- workspaces/orchestrator/plugins/orchestrator/catalog-info.yaml
Part of https://issues.redhat.com/browse/RHIDP-5574
Backstage sets this annotations automatically when the catalog-info.yaml is loaded from GitHub, so it's not needed:
```yaml
backstage.io/source-location: url:...
backstage.io/view-url: ...
backstage.io/edit-url: ....
```
> chore: update multiple catalog-info.yamls

- workspaces/orchestrator/.changeset/two-bears-sing.md
- workspaces/orchestrator/plugins/orchestrator-backend/src/helpers/filterBuilder.ts
Fix a typo in FilterBuilder error message
Fixes [FLPATH-2037](https://issues.redhat.com/browse/FLPATH-2037)
> fix(orchestrator): typo in FilterBuilder error message

- workspaces/orchestrator/app-config.yaml
The only purpose is to simplify dev-env setup when working with RBAC
> chore(orchestrator): add orchestror among pluginsWithPermission

- workspaces/global-floating-action-button/.changeset/funny-jars-itch.md
- workspaces/global-floating-action-button/plugins/global-floating-action-button/README.md
- workspaces/global-floating-action-button/plugins/global-floating-action-button/app-config.dynamic.yaml
- workspaces/global-floating-action-button/plugins/global-floating-action-button/dev/ExampleComponent/ExampleComponent.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/dev/ExampleComponent/ExampleFetchComponent.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/dev/index.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/package.json
- workspaces/global-floating-action-button/plugins/global-floating-action-button/report.api.md
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/DynamicGlobalFloatingActionButton.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/FAB.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/FABWithSubmenu.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/FloatingButton.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/NullComponent.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/hooks/useFabMountPoints.ts
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/plugin.test.ts
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/plugin.ts
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/types.ts
- workspaces/global-floating-action-button/yarn.lock
**Resolves:**
https://issues.redhat.com/browse/RHIDP-5402
> feat(fab): created dynamic fab to be integrated in the RHDH app

- workspaces/orchestrator/.changeset/strange-fishes-wait.md
- workspaces/orchestrator/plugins/orchestrator-common/src/permissions.ts
With this change, the RBAC UI can list both `orchestrator.workflow` and `orchestrator.workflow.use` permissions.
Fixes: FLPATH-2032
> fix(orchestrator): list orchestrator.workflow.use in the RBAC UI

- workspaces/orchestrator/.changeset/tasty-boxes-accept.md
- workspaces/orchestrator/docs/Permissions.md
- workspaces/orchestrator/docs/rbac-policy.csv
- workspaces/orchestrator/plugins/orchestrator-common/src/permissions.ts
Changing the `read` policy to `update` of the `orchestrator.workflow.use` permission to closer align with other plugins.
Documentation updated.
Fixes: FLPATH-2033
> fix(orchestrator): use 'update' policy for orchestrator.workflow.use

- CONTRIBUTING.md
Updates the CONTRIBUTING.md doc to include a `yarn install` in a new workspace before generating plugins. Without the `yarn install`, I was given this error:
```
Internal Error: @internal/test-workspace@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
at z0.getCandidates (/Users/jcollier/git/rhdh-plugins/.yarn/releases/yarn-3.8.7.cjs:436:5149)
```
> chore: add explicit yarn install before creating plugin in new workspace to CONTRIBUTING.md

- workspaces/lightspeed/.changeset/modern-ways-shave.md
- workspaces/lightspeed/plugins/lightspeed/package.json
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/hooks/index.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/useIsMobile.ts
- workspaces/lightspeed/yarn.lock
https://issues.redhat.com/browse/RHDHPAI-483
This PR upgrades to the latest PF and includes following changes:
- Add resizable drawers to the conversation history
- close conversation history by default on smaller screens.
---
**Conversation history is closed by default in smaller screens:**
---
**Resizable drawers:**
https://github.com/user-attachments/assets/86a05cd9-3aa6-4f53-923d-86b58ad7c76b
> fix(lightspeed): Add resizable drawers and default to closed drawers on smaller screens

- .github/CODEOWNERS
I reordered the plugins alphabetically and aligned the plugins that were in the past (who knows the future), driven by the UI team.
I still like that individuals feel responsible for these plugins, but with different timezones, it's great that more people can review/approve PRs.
> chore: update codeowners for multiple plugins

- workspaces/global-floating-action-button/.changeset/angry-eggs-agree.md
- workspaces/global-floating-action-button/plugins/application-provider-test/README.md
- workspaces/global-floating-action-button/plugins/application-provider-test/app-config.dynamic.yaml
- workspaces/global-floating-action-button/plugins/application-provider-test/dev/index.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/report.api.md
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/CrashProvider.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/TestCardOne.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/TestCardTwo.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/TestPage.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/TestProviderOne.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/components/TestProviderTwo.tsx
- workspaces/global-floating-action-button/plugins/application-provider-test/src/plugin.ts
Improved test plugin two test the RHDH change with two providers. /cc @debsmita1 :)
I now also added a CrashProvider. It's not needed that this is handled in rhdh yet, but it's good to have a test component for that.
The link in the README depends on https://github.com/redhat-developer/rhdh/pull/2199 and should work soon. :)
> feat(application-provider-test): add CrashProvider and exports now two seperate context providers and cards

- workspaces/orchestrator/.changeset/silver-eagles-notice.md
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
resolve [FLPATH-2001](https://issues.redhat.com/browse/FLPATH-2001)
long list case:
> fix(orchestrator):add view variables dialog

- workspaces/marketplace/.changeset/short-berries-perform.md
- workspaces/marketplace/app-config.yaml
- workspaces/marketplace/examples/all-packages.yaml
- workspaces/marketplace/examples/packages/tekton.yaml
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/report.api.md
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePackageProcessor.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePackageProcessor.ts
- workspaces/marketplace/plugins/marketplace-common/report.api.md
- workspaces/marketplace/plugins/marketplace-common/src/types.ts
Emitting `partOf/HasPart` relationship in `MarketplacePackageProcessor`.
---
> feat(marketplace): add package entity relationship with plugin entity

- workspaces/orchestrator/.changeset/wicked-hats-give.md
- workspaces/orchestrator/.gitignore
- workspaces/orchestrator/app-config.yaml
- workspaces/orchestrator/plugins/orchestrator-backend/src/service/DevModeService.ts
improved devMode to make multi platform development easier
- Added Podman support (opinionated, people can use Podman. Docker is still kept as default) 
- Added M1 (ARM) Mac support
- Added DB persistence in sonata flow dev mode image (optional). This will improve the startup time of the dev mode container. 
- Moved temp directory to `.devModeTemp` folder under the `backend` plugin directory to maintain podman support. Podman does not have access to `/tmp` by default.
> fix(orchestrator): improved devMode, added podman and macos support

- workspaces/global-header/.changeset/clever-forks-double.md
- workspaces/global-header/plugins/global-header/app-config.dynamic.yaml
- workspaces/global-header/plugins/global-header/dev/index.tsx
- workspaces/global-header/plugins/global-header/report.api.md
- workspaces/global-header/plugins/global-header/src/components/Divider/Divider.tsx
- workspaces/global-header/plugins/global-header/src/components/GlobalHeaderComponent.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderButton/HeaderButton.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/CreateDropdown.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/MenuSection.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ProfileDropdown.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/RegisterAComponentSection.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/SoftwareTemplatesSection.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderIcon/HeaderIcon.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderIconButton/HeaderIconButton.tsx
- workspaces/global-header/plugins/global-header/src/components/MenuItemLink/MenuItemLinkContent.tsx
- workspaces/global-header/plugins/global-header/src/components/NotificationButton/NotificationButton.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchComponent.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchInput.tsx
- workspaces/global-header/plugins/global-header/src/components/Spacer/Spacer.tsx
- workspaces/global-header/plugins/global-header/src/components/SupportButton/SupportButton.test.tsx
- workspaces/global-header/plugins/global-header/src/components/SupportButton/SupportButton.tsx
- workspaces/global-header/plugins/global-header/src/defaultMountPoints/defaultMountPoints.tsx
- workspaces/global-header/plugins/global-header/src/hooks/useNotificationCount.ts
- workspaces/global-header/plugins/global-header/src/plugin.ts
- workspaces/global-header/plugins/global-header/src/types.ts
* Revert https://github.com/redhat-developer/rhdh-plugins/commit/aaebac0e1338b65b3cca88a89c781bed25cfa658 because I still believe we don't need this specific code to detect if notification plugin is installed or not.
* Removed ComponmentType to simplify API and
* Added/fixed layout prop to the header components to support some responsive design tweaks in dynamic plugin config. see incl. app-config.
* Moved some local styles to the incl. app config as well
* Hide the username on xs and sm screen sizes to improve responsive layout
> feat(global-header): add support for layout option in app-config and improved responsive layout a bit

- workspaces/orchestrator/.changeset/cool-cats-explain.md
- workspaces/orchestrator/plugins/orchestrator/src/components/InfoDialog.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
resolve [FLPATH-1080](https://issues.redhat.com/browse/FLPATH-1080)
https://github.com/user-attachments/assets/2f1e7503-e0d0-498c-ab0a-6e840402beb2
> fix(orchestarator):Disable abort when workflow execution does not exist

- workspaces/bulk-import/.changeset/gorgeous-ants-hear.md
- workspaces/bulk-import/plugins/bulk-import/src/hooks/useAddedRepositories.ts
**Fixing** : [RHIDP-5626](https://issues.redhat.com/browse/RHIDP-5626)
**Description of Issue** : 
When changing `sort column`, `sort order`, `Page Number`, or `Page Size`, the Imports API is being called twice:
**1. First call**: with the current parameter values.
**2. Second call**: with the updated (new) parameter values.
Below is the screen Recording demonstrating the above issue 
https://github.com/user-attachments/assets/b153825b-1860-4528-b8bc-dc2bd9cd4f44
**Root Cause** 
React Query’s `useQuery` automatically refetches when the window regains focus. Clicking on the UI to change the sort column, page number, page size, or sort order causes the window to regain focus, triggering an additional refetch. Additionally, since these interactions also update state, another API call is …
> fix(bulk-import): fixing extra apis call on added repo list page

- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Temporarily disable the `retrigger` feature (introduced by #300) as a workaround for FLPATH-2135.
We will re-enable the feature once the SonataFlow introduces sufficient fixes.
> fix(orchestrator): temporarily disable the Retrigger feature

- workspaces/marketplace/.changeset/fifty-geckos-smell.md
- workspaces/marketplace/plugins/marketplace-common/package.json
- workspaces/marketplace/plugins/marketplace-common/report.api.md
- workspaces/marketplace/plugins/marketplace-common/src/api/MarketplaceBackendClient.ts
- workspaces/marketplace/yarn.lock
Try to solve:
```
➤ YN0002: │ @red-hat-developer-hub/backstage-plugin-marketplace-common@npm:0.1.1 [ea14c] doesn't provide react (pdd725), requested by @backstage/core-plugin-api
➤ YN0002: │ @red-hat-developer-hub/backstage-plugin-marketplace-common@npm:0.1.1 [ea14c] doesn't provide react-dom (pa2514), requested by @backstage/core-plugin-api
➤ YN0002: │ @red-hat-developer-hub/backstage-plugin-marketplace-common@npm:0.1.1 [ea14c] doesn't provide react-router-dom (paa342), requested by @backstage/core-plugin-api
```
when running `yarn export-dynamic` on the rhdh backend wrapper.
> fix(marketplace): remove core-plugin-api dependency from common

- workspaces/marketplace/.changeset/smart-balloons-confess.md
- workspaces/marketplace/app-config.yaml
- workspaces/marketplace/plugins/marketplace/src/hooks/useFilteredPlugins.ts
Just adds a default sort to the use / get filtered plugins API call
Without this:
With this change:
> fix(marketplace): apply default sorting to filtered plugins api call

- workspaces/marketplace/.changeset/shaggy-zoos-fetch.md
- workspaces/marketplace/package.json
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/package.json
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/report.api.md
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/module.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/module.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/BaseEntityProvider.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/MarketplaceCollectionProvider.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/MarketplacePackageProvider.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/MarketplacePluginProvider.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/index.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/types.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/utils/file-utils.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/utils/file-utils.ts
- workspaces/marketplace/yarn.lock
This PR adds three new marketplace providers to add entities into the catalog.  The providers reads the plugins, package and collection entity metadata from RHDH image and adds to the catalog.
```
catalog.addEntityProvider(new MarketplacePackageProvider(taskRunner));
catalog.addEntityProvider(new MarketplacePluginProvider(taskRunner));
// catalog.addEntityProvider(new MarketplaceCollectionProvider(taskRunner)); // not registered for 1.5 
```
> feat(marketplace): Add marketplace providers to add entities into the catalog

- workspaces/adoption-insights/plugins/adoption-insights-backend/README.md
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/PostgresAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/SqliteAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/event-database.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/plugin.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/types/event.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/date.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/date.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/validation/event-request.ts
https://issues.redhat.com/browse/RHDHPAI-658
This PR contains following changes:
- Add `grouping` query param configuration to provide fine grain control to the consumers. Now users can explicitly fetch the queries based on their need, if not then backend will choose them a better grouping strategy based on the date interval.
- added `hourly` grouping strategy to get data points for every hour in a day.
- Updated the documentation.
Screenshots:
> feat(adoption-insights): add grouping configuration in insights endpoints.

- workspaces/marketplace/.changeset/small-fireants-care.md
- workspaces/marketplace/packages/cli/src/commands/generate/index.ts
- workspaces/marketplace/plugins/marketplace/package.json
- workspaces/marketplace/plugins/marketplace/src/components/CodeEditor.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
- workspaces/marketplace/yarn.lock
Add a new `CodeEditor` component and show initial YAML from the packages.
Hopefully resolves https://issues.redhat.com/browse/RHIDP-6278 without unit tests yet. But I like to release this to see if its working fine on RHDH / on a cluster.
The unreachable /install page looks now like this:
I implemented this with a React context so that we don't need to "control" and rerender this form on any change.
The Buttons can get and set the latest editor value. The copy button works already but should have a alert/tooltip "copied" later.
> feat(marketplace): add monaco editor

- workspaces/global-header/.changeset/quiet-bulldogs-battle.md
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/CreateDropdown.tsx
Fixing : [Rename the 'Create' that appears on the Global header ](https://issues.redhat.com/browse/RHIDP-6164)
Screenshot from RHDH-Plugin
ScreenShot from RHDH
> feat(global-header): changing create to self-service

- workspaces/marketplace/.changeset/bright-stingrays-invite.md
- workspaces/marketplace/packages/cli/cli-report.md
- workspaces/marketplace/packages/cli/package.json
- workspaces/marketplace/packages/cli/src/commands/index.ts
- workspaces/marketplace/packages/cli/src/commands/init/index.ts
- workspaces/marketplace/yarn.lock
Add new `marketplace-cli` command, its not 100% accurate but it could help to setup new plugin and package YAMLs.
It automatically detects if its running in a workspace.
> feat(marketplace): add new marketplace-cli init command

- workspaces/global-header/.changeset/mean-weeks-tie.md
- workspaces/global-header/docs/index.md
- workspaces/global-header/plugins/global-header/app-config.dynamic.yaml
- workspaces/global-header/plugins/global-header/dev/index.tsx
- workspaces/global-header/plugins/global-header/report.api.md
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/HeaderDropdownComponent.test.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/HeaderDropdownComponent.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/StarredDropdown.test.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/StarredDropdown.tsx
- workspaces/global-header/plugins/global-header/src/defaultMountPoints/defaultMountPoints.tsx
- workspaces/global-header/plugins/global-header/src/plugin.ts
Fixes - [RHDHPAI-664](https://issues.redhat.com/browse/RHDHPAI-664)
This PR adds a new starred entities dropdown to the global header.
https://github.com/user-attachments/assets/d5e79058-1484-4173-af3e-f7db6b5917dc
> feat(global-header): add starred entities dropdown to header

- workspaces/global-header/.changeset/tall-zoos-pump.md
- workspaces/global-header/packages/app/src/apis.ts
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchBar.test.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchBar.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchResultItem.test.tsx
- workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchResultItem.tsx
- workspaces/global-header/plugins/global-header/src/hooks/useDebouncedCallback.ts
https://issues.redhat.com/browse/RHIDP-6480
Backstage search component emits the Search analytics data such as `search`, `discover` events with additional metadata but the custom search component in global header does not emit the search analytics data.
This PR fixes by emitting `search` and `discover` events and adds debounce on InputChange to avoid frequent execution of callbacks.
Setup analytics in the application in `/packages/app/src/apis.ts`.
```
createApiFactory(analyticsApiRef, {
captureEvent: (event:AnalyticsEvent) => {
console.log('Captured event:', event);
},
}), 
```
**Before:**
`search` event is missing
---
on clicking any search results it is missing `discover` event.
**After:**
onSearch:
---
on clicking any search results:
> fix(global-header): Emit search analytics data from global header searchbar

- workspaces/repo-tools/packages/cli/src/lib/workspaces/templates/workspace/package.json.hbs
- Since this has been merged https://github.com/backstage/backstage/pull/27630, updated @backstage/repo-tools to use version syntax
- Removed Usages of @spotify/prettier-config as we can now use @backstage/cli/config/prettier instead (from backstage version 1.34.0 onwards)
> chore: update templates used in create-workspace command

- workspaces/marketplace/.changeset/twenty-beers-talk.md
- workspaces/marketplace/.changeset/unlucky-lemons-reply.md
- workspaces/marketplace/plugins/marketplace/src/components/CodeEditor.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePackageInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
Incl. 2 fixes:
1. add workaround to reduce code editor bundled size (js and js.map)
2. show error message when the YAML example could not be applied
File size before:
```
cd workspaces/marketplace/plugins/marketplace
rm -rf dist-dynamic
npx --yes @janus-idp/cli package export-dynamic-plugin
du -hs dist-dynamic/dist-scalprum/static/* | grep 'M[^a-z]'
4.7M	dist-dynamic/dist-scalprum/static/5804.5bb67286.chunk.js
20M	dist-dynamic/dist-scalprum/static/5804.5bb67286.chunk.js.map
```
With this change:
```
rm -rf dist-dynamic
npx --yes @janus-idp/cli package export-dynamic-plugin
du -hs dist-dynamic/dist-scalprum/static/* | grep 'M[^a-z]'
du -hs dist-dynamic/dist-scalprum/static/* | grep 'M[^a-z]'
3.7M	dist-dynamic/dist-scalprum/static/23.143aaf50.chunk.js
16M …
```
> fix(marketplace): reduce bundle size to run in RHDH and show error when YAML isn't valid

- workspaces/adoption-insights/plugins/analytics-module-adoption-insights/report.api.md
- workspaces/adoption-insights/plugins/analytics-module-adoption-insights/src/api/AdoptionInsightsAnalyticsApi.test.ts
- workspaces/adoption-insights/plugins/analytics-module-adoption-insights/src/api/AdoptionInsightsAnalyticsApi.ts
https://issues.redhat.com/browse/RHDHPAI-678
Add pending queue to park the events without user information, wait till user identity to resolvde and re-queue the events to track them with user information. 
- navigate to Adoption insights page and notice the count on the techdocs chart
- Click on a link from techdocs charts which opens a page in a new tab.
- Now go back to the adoption-insights tab, refresh the page after few seconds to see the count is increased.
> fix(adoption-insights): process events when the user identity is ready

- workspaces/adoption-insights/plugins/adoption-insights-backend/src/controllers/EventApiController.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/controllers/EventApiController.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/SqliteAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/types/event.ts
- workspaces/adoption-insights/plugins/adoption-insights/dev/__data__/techdocs.ts
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Techdocs/Techdocs.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/types/index.ts
Fixes:
https://issues.redhat.com/browse/RHDHPAI-677
**Before:**
**After:**
Name column now uses `site_name` from techdocs metadata.
> fix(adoption-insights): fix name column in the techdocs chart

- workspaces/adoption-insights/package.json
- workspaces/adoption-insights/plugins/adoption-insights-backend/package.json
- workspaces/adoption-insights/plugins/adoption-insights/app-config.dynamic.yaml
- workspaces/adoption-insights/plugins/adoption-insights/package.json
- workspaces/adoption-insights/plugins/adoption-insights/report.api.md
- workspaces/adoption-insights/plugins/adoption-insights/src/index.ts
- workspaces/adoption-insights/plugins/adoption-insights/src/plugin.ts
This PR contains the following changes:
1. Add and export Insights plugin Icon
2. Fix MUI v5 classname prefix
3. Update the header to "Adoption Insights"
> fix(adoption-insights): Add adoption insights plugin icon

- workspaces/global-floating-action-button/.changeset/dirty-crabs-invent.md
- workspaces/global-floating-action-button/.changeset/perfect-years-scream.md
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/CustomFab.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/FABWithSubmenu.tsx
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/index.ts
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/utils.test.ts
- workspaces/global-floating-action-button/plugins/global-floating-action-button/src/utils.ts
**Fixes:** https://issues.redhat.com/browse/RHIDP-6463
I noticed two issues when testing the global-floating-action-button plugin with RHDH and installed it with:
```
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root ~/git/redhat-developer/rhdh/dynamic-plugins-root --dev --clean
```
I then enabled the plugin with:
```yaml
dynamicPlugins:
frontend:
red-hat-developer-hub.backstage-plugin-global-floating-action-button:
mountPoints:
- mountPoint: application/listener
importName: DynamicGlobalFloatingActionButton
red-hat-developer-hub.backstage-plugin-bulk-import:
mountPoints:
- mountPoint: global.floatingactionbutton/config
importName: BulkImportPage
config:
slot: page-end
icon: bulkImportIcon
label: 'Bulk import'
toolTip: 'Register multiple repositories in bulk' …
```
> fix(global-floating-action-button): fix crash and design issues when testing locally

- workspaces/marketplace/.changeset/funny-donkeys-occur.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePackageContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx
This adds the default Grid spacing that isn't applied when the plugin is loaded as dynamic plugin.
Before:
With this PR:
> fix(marketplace): add missing grid spacing when loaded as dynamic plugin

- workspaces/adoption-insights/plugins/adoption-insights/src/components/CatalogEntities/CatalogEntities.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Header/Header.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Header/__tests__/Header.test.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/hooks/useCatalogEntities.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/utils/__tests__/constants.test.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/utils/constants.ts
- workspaces/adoption-insights/plugins/adoption-insights/src/utils/utils.ts
https://issues.redhat.com/browse/RHDHPAI-715
https://issues.redhat.com/browse/RHDHPAI-706
Add Last 28 days to date range dropdown. And catalog entities filter issue.
Before
After
> fix(adoption-insights): add last 28 days and catalog filter

- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
https://issues.redhat.com/browse/RHDHPAI-714
Avoid duplicate column grouping by making the kind value lowercase
Before: **( guests row is repeating)**
After:
> fix(adoption-insights): make kind value lowercase to avoid duplicates

- workspaces/ai-integrations/.changeset/crazy-clouds-shake.md
- workspaces/ai-integrations/app-config.yaml
- workspaces/ai-integrations/babel.config.js
- workspaces/ai-integrations/packages/backend/src/index.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/config.d.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/package.json
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/report.api.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/BridgeResourceConnector.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/BridgeResourceConnector.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/index.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/types.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/module.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/module.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/processors/RHDHRHOAIReaderProcessor.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/processors/index.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/ModelCatalogResourceEntityProvider.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/RHDHRHOAIEntityProvider.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/config.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/index.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/types.ts
- workspaces/ai-integrations/yarn.lock
Initial code drop of the model catalog plugin originally under development in the [redhat-ai-dev/rhdh-plugins fork](https://github.com/redhat-ai-dev/rhdh-plugins/tree/main/workspaces/rhdh-ai). 
It's largely a straightforward copy/paste, with a couple (small) test additions and handling renames from rhdh-ai -> ai-integration.
Verified by configuring a [model-catalog-bridge](https://github.com/redhat-ai-dev/model-catalog-bridge/) instance on my laptop, and setting the environment variables in [README.md of the workspace](https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/ai-integrations/README.md), then running:
1) `yarn install`
2) `yarn dev`
> feat(ai-integrations): Initial code drop of model catalog backend module

- workspaces/global-floating-action-button/.changeset/six-camels-bow.md
- workspaces/global-floating-action-button/.changeset/wet-mayflies-pull.md
- workspaces/global-floating-action-button/plugins/application-listener-test/report.api.md
- workspaces/global-floating-action-button/plugins/application-listener-test/src/index.ts
- workspaces/global-floating-action-button/plugins/application-provider-test/report.api.md
- workspaces/global-floating-action-button/plugins/application-provider-test/src/index.ts
Manually installed both plugins into rhdh:
```
cd rhdh-plugins/workspaces/global-floating-action-button/plugins/application-listener-test
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root ~/git/redhat-developer/rhdh/dynamic-plugins-root --dev --clean
cd rhdh-plugins/workspaces/global-floating-action-button/plugins/application-provider-test
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root ~/git/redhat-developer/rhdh/dynamic-plugins-root --dev --clean
```
Configured rhdh like this:
```yaml
dynamicPlugins:
frontend:
red-hat-developer-hub.backstage-plugin-application-provider-test:
dynamicRoutes:
- path: /application-provider-test-page
importName: TestPage
mountPoints:
- mountPoint: application/provider
importName: CrashProvider
- …
```
> feat(global-fab): add test components without errorboundaries

- workspaces/orchestrator/.changeset/flat-shirts-beg.md
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/RunButton.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsTabContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTabContent.tsx
resolve  [FLPATH-2232](https://issues.redhat.com/browse/FLPATH-2232)
Before:
https://github.com/user-attachments/assets/28780966-a9a0-4b77-befe-78f2b3633bbb
After:
https://github.com/user-attachments/assets/40c66da0-d865-495f-acec-704a9a842023
> fix(orchestrator):  fix responsiveness of the WorkflowPage

- workspaces/marketplace/.changeset/chilly-pumas-heal.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.tsx
**Resolve** : https://issues.redhat.com/browse/RHIDP-6309
**Description** :  Remove View Plugins button from No Plugins / Empty Catalog Page
Before Change 
After Changes
> feat(marketplace): removing view plugins button

- workspaces/orchestrator/.changeset/wise-feet-bow.md
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTable.tsx
- workspaces/orchestrator/plugins/orchestrator/src/constants.ts
- workspaces/orchestrator/plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
resolve [FLPATH-2201](https://issues.redhat.com/browse/FLPATH-2201)
> fix(orchestrator): Add Workflow Status to WorkflowsTable

- workspaces/adoption-insights/.changeset/evil-rice-itch.md
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
https://github.com/redhat-developer/rhdh-plugins/issues/607     
The failing API contains a sub query without an alias (alias was wrongly placed in the query), since sub-query alias was made optional in Postgres 16 onwards so it is not an issue with latest Postgres db versions, but it errors out in Postgres 15 or below. RHDH setup uses 
This PR fixes database query failure for the earlier versions of Postgres. i.e Postgres 15 or below
**Before:**
---
**After:**
> fix(adoption-insights): fix subquery alias in total_users endpoint to support older PG versions

- workspaces/ai-integrations/plugins/ai-experience/src/components/LearnSection/CardWrapper.tsx
- workspaces/ai-integrations/plugins/ai-experience/src/components/Links/ViewMoreLink.tsx
- workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/CardWrapper.tsx
- workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/ModelSection.tsx
- workspaces/ai-integrations/plugins/ai-experience/src/components/TemplateSection/CardWrapper.tsx
- workspaces/ai-integrations/plugins/ai-experience/src/components/TemplateSection/TemplateSection.tsx
This PR contains following changes:
- Fix the Link component import so the page transitions are smooth.
- removed "target=_blank" property from the UI to open links in the same page.
> fix(ai-experience): links should open pages in the same tab

- workspaces/ai-integrations/.changeset/brown-peaches-try.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/package.json
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/report.api.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/BridgeResourceConnector.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/BridgeResourceConnector.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/processors/RHDHRHOAIReaderProcessor.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/ModelCatalogResourceEntityProvider.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/ModelCatalogResourceEntityProvider.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/__snapshots__/ModelCatalogResourceEntityProvider.test.ts.snap
- workspaces/ai-integrations/yarn.lock
This PR updates the entity provider and custom processor to handle model catalog JSON objects rather than the raw entities it used to send. Now, both will receive arrays of `ModelCatalog` from the Model Catalog Bridge, and convert them into their corresponding entities. 
In summary:
- Updates Model Catalog EntityProvider to use the JSON object provided by the bridge
- Updates Model Catalog Custom Processor to use the JSON object provided by the bridge
- Calls the Model Catalog generator functions on the JSON object to convert the JSON objects to Backstage catalog entities
- Updates the generator functions to handle sanitization of `metadata.name` and `metadata.tags[]`
_Very_ basic test for the catalog entity provider
> RHDHPAI-611: Convert the model catalog plugin to receive catalog JSON objects

- workspaces/global-header/.changeset/calm-cherries-wonder.md
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/HeaderDropdownComponent.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/MenuSection.tsx
- workspaces/global-header/plugins/global-header/src/components/LogoutButton/LogoutButton.tsx
- workspaces/global-header/plugins/global-header/src/components/MenuItemLink/MenuItemLink.tsx
fixes https://issues.redhat.com/browse/RHIDP-6537
- use more "semantic" MUI components (e.g., `ListSubHeader`)
- remove the MenuList hover style override (a hover style is also in PatternFly)
- make sure `MenuItem`s are always the direct children of the `Menu` for MUI to pick them up for keyboard support
https://github.com/user-attachments/assets/40e63685-cd42-4e13-a42e-40afc8ccc3fd
> fix(global-header): Add keyboard support to global-header to improve a11y

- CONTRIBUTING.md
Made some changes to the Plugin Owner Responsibilities section to make it clearer that plugin owners need to request for write access to the repository and explicitly mention the types of PRs they are supposed to be reviewing/merging.
> update plugin owner expectations

- workspaces/lightspeed/.changeset/shy-carrots-jog.md
- workspaces/lightspeed/packages/app/e2e-tests/fixtures/responses.ts
- workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts
- workspaces/lightspeed/plugins/lightspeed/src/api/LightspeedApiClient.ts
- workspaces/lightspeed/plugins/lightspeed/src/api/api.ts
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/const.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/__tests__/useConversationMessages.test.tsx
- workspaces/lightspeed/plugins/lightspeed/src/hooks/index.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/useConversationMessages.ts
- workspaces/lightspeed/plugins/lightspeed/src/types.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/__tests__/lightspeed-chatbot-utils.test.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/lightspeed-chatbox-utils.ts
This PR contains following changes:
- Removes the `POST /conversations` endpoint.
- use `v1/query` without conversation_id to create a new conversation_id for the first conversation.
- Add inline error messages 
https://github.com/user-attachments/assets/6a59bd0b-89a9-4b33-abfa-0554b9da04d0
---
Inline error messages:
How to test:
1. clone [road-core service repo](https://github.com/road-core/service) & install python dependencies
2. save token to the team cluster in a file called `team_cluster_key.txt`
3. save following to a file called `rcsconfig.yaml`
```
llm_providers:
- name: team_cluster
type: openai
url: "https://ibm-granite-8b-code-instruct-3scale-apicast-production.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com:443/v1"
credentials_path: team_cluster_key.txt
disable_model_check: …
```
> feat(lightspeed): align with road-core API endpoints

- workspaces/orchestrator/.changeset/six-cats-heal.md
- workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowRunsTabContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
- workspaces/orchestrator/plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
resolve [FLPATH-2253](https://issues.redhat.com/browse/FLPATH-2253)
> fix(orchestrator):Add status icons

- workspaces/orchestrator/.changeset/great-pumas-sin.md
- workspaces/orchestrator/plugins/orchestrator-backend/src/plugin.ts
- workspaces/orchestrator/plugins/orchestrator-backend/src/routerWrapper/index.ts
- workspaces/orchestrator/plugins/orchestrator-backend/src/service/router.ts
This requires #418 
We are switching from the Janus-developed audit logger to its new upstream counterpart which is part of the Backstage `1.36.0` or RHDH `1.6+`.
So far all events have default (means `low`) severity. We can increase that later.
With this setting, mind changing configuration for testing: https://backstage.io/docs/next/backend-system/core-services/auditor/#severity-levels-and-default-mappings
---
Example event in the log:
```
2025-04-16T11:26:48.390Z orchestrator info orchestrator.execute-workflow isAuditEvent=true eventId="execute-workflow" severityLevel="medium" actor={"actorId":"user:development/guest","ip":"::1","hostname":"localhost","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"} …
```
> chore(orchestrator): use upstream AuditorService

- workspaces/ai-integrations/.changeset/cold-papers-listen.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/module.ts
add a log message around our location extension as part of diagnosing the location type not getting registered when we run as a dynamic plugin in RHDH (vs. running via yarn from out laptop)
- [ /] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [ n/a] Added or Updated documentation
- [ n/a] Tests for new functionality and regression tests for bug fixes
- [ n/a] Screenshots attached (for UI changes)
> add log message around registering the 'rhdh-rhoai-bridge' location type

- workspaces/orchestrator/.changeset/cool-wasps-add.md
- workspaces/orchestrator/plugins/orchestrator-backend/package.json
- workspaces/orchestrator/plugins/orchestrator-form-widgets/package.json
- workspaces/orchestrator/plugins/orchestrator/package.json
- workspaces/orchestrator/plugins/scaffolder-backend-module-orchestrator/package.json
- workspaces/orchestrator/yarn.lock
The latest 3.5.0 is failing in PNC for unknown reason (the process is killed, no error shown). This revert enables us to keep releasing 1.6.0-rc.X versions while looking into the issue with upgrade in parallel.
The issue is not happening locally, with yarn and node versions equal.
> chore(orchestrator): revert @janus-idp/cli to 3.2.0

- workspaces/ai-integrations/.changeset/wild-schools-attend.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/package.json
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.ts
- workspaces/ai-integrations/yarn.lock
This PR updates the model catalog plugin to add the techdocs annotation (`backstage.io/techdocs-ref`) to the generated `ai-model` Resource entities when they are generated.
> feat(ai-integrations): Provide support for techdocs when present on the Model Catalog JSON object

- workspaces/ai-integrations/.changeset/tasty-owls-rest.md
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.test.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/clients/ModelCatalogGenerator.ts
- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/providers/__snapshots__/ModelCatalogResourceEntityProvider.test.ts.snap
Fixes the following small bugs in the model catalog plugin:
- Owner name not being set properly --> Properly sets the entity owner by prepending `user:` when generating the entities
- License information missing --> Adds the License URL to the model component if present
- Authentication information missing --> Adds the `auth-required` / `auth-not-required` tags when relevant to the model server component
> fix(ai-integrations): Properly generate user, license, and authentication in catalog entities

- workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/ModelSection.tsx
make model displayName optional in ai homepage, fallback to the model name if the displayName is missing.
> fix(ai-experience): make model displayName optional in ai homepage

- workspaces/openshift-image-registry/.changeset/five-cars-dance.md
- workspaces/openshift-image-registry/plugins/openshift-image-registry/package.json
- workspaces/openshift-image-registry/yarn.lock
remove unused devdependency @types/node to reduce number of automated PRs that updates this package
see https://github.com/redhat-developer/rhdh-plugins/pulls?q=is%3Apr+update+dependency+%40types%2Fnode
> chore(openshift-image-registry): remove unused devdependency @types/node

- workspaces/marketplace/.changeset/ten-tigers-dream.md
- workspaces/marketplace/packages/cli/src/commands/generate/index.ts
use namespace parameter also for packages location
When running the generate command in rhdh as below, it doesn't create the namespace for the Location entity.
```
cd rhdh
npx -y @red-hat-developer-hub/marketplace-cli generate --namespace rhdh -p dynamic-plugins.default.yaml -o catalog-entities/marketplace/packages
```
> fix(marketplace): use namespace also for packages location

- workspaces/theme/.changeset/plenty-apples-remain.md
- workspaces/theme/plugins/theme/app-config.dynamic.yaml
- workspaces/theme/plugins/theme/package.json
- workspaces/theme/plugins/theme/report.api.md
- workspaces/theme/plugins/theme/src/index.ts
- workspaces/theme/plugins/theme/src/themes.tsx
Part of https://issues.redhat.com/browse/RHIDP-7321
This change allows us to load the theme dynamically. With a wrapper or later as a container image.
Could be tested with:
```yaml
cd workspaces/theme/plugins/theme
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root ~/git/rhd/rhdh/dynamic-plugins-root --clean --dev
```
Dynamic plugins configuration:
```yaml
dynamicPlugins:
frontend:
red-hat-developer-hub.backstage-plugin-theme:
appIcons:
- importName: LightIcon
name: lightIcon
- importName: DarkIcon
name: darkIcon
themes:
- id: light-dynamic
icon: lightIcon
importName: lightThemeProvider
title: Light Dynamic
variant: light
- icon: darkIcon
id: dark-dynamic
importName: darkThemeProvider
title: Dark Dynamic
variant: dark
```
I will work also on an update in …
> feat(theme): add support to load the theme as dynamic plugin

- workspaces/orchestrator/plugins/orchestrator-backend/package.json
- workspaces/orchestrator/plugins/scaffolder-backend-module-orchestrator/package.json
This CLI option was removed between janus-cli `3.2.0.` and recent `3.5.0`.
Let's give it try this way.
> chore(orchestrator): remove --no-embed-as-dependencies from export-dynamic for 3.5.0 janus-cli

- workspaces/sandbox/plugins/sandbox/package.json
Mark Sandbox plugin as private as it is not supposed to be published to npm.
> fix(sandbox-plugin): make sandbox plugin private

- workspaces/sandbox/README.md
- workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogPage.tsx
Hide the footer temporarily, until we update the backend for the activation-code. See: https://issues.redhat.com/browse/SANDBOX-1161
Also some minor Readme fixes and removal of outadated information.
> fix(sandbox): hide footer, minor readme fixes

- workspaces/sandbox/make/sandbox.mk
- workspaces/sandbox/plugins/sandbox/src/api/RegistrationBackendClient.tsx
- workspaces/sandbox/plugins/sandbox/src/components/Modals/AnsibleLaunchInfoModal.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxActivities/SandboxActivitiesGrid.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxActivities/SandboxActivitiesPage.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogCardButton.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogGrid.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogPage.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxHeader.tsx
WRT: https://issues.redhat.com/browse/RHDHPAI-792
> fix(sandbox): some css updates

- workspaces/homepage/.changeset/happy-boxes-explode.md
- workspaces/homepage/plugins/dynamic-home-page/src/components/HomePage.tsx
Fixes : https://issues.redhat.com/browse/RHIDP-7009
https://github.com/user-attachments/assets/2040236b-d317-485d-94ad-3e48bfbe975d
https://github.com/user-attachments/assets/41f76061-f980-4721-bca4-65c8972689d4
For testing 
1. Take this PR change in  RHDH 
```
npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root  <path-to=rhdh>/rhdh/dynamic-plugins-root --dev
```
2. Add `Top Visited` and `Recent Visited` Card in homepage by adding below config
```
dynamicPlugins:
rootDirectory: dynamic-plugins-root
frontend:
red-hat-developer-hub.backstage-plugin-dynamic-home-page:
dynamicRoutes:
- path: /
importName: DynamicHomePage
mountPoints:
- mountPoint: application/listener
importName: VisitListener
- mountPoint: home.page/cards
importName: RecentlyVisitedCard
config: …
```
> feat(homepage): fixing title in top & recent card on refresh

- workspaces/sandbox/plugins/sandbox/src/api/RegistrationBackendClient.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxActivities/SandboxActivitiesGrid.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxHeader.test.tsx
- workspaces/sandbox/plugins/sandbox/src/components/SandboxHeader.tsx
It contains the following fixes:
- fix the page title:
- add back the background color for the Activities page in light mode 
- improve custom error message for phone verification, as suggested in https://github.com/redhat-developer/rhdh-plugins/pull/752/files#r2084893090
> fix(sandbox): fix page title

- workspaces/orchestrator/.changeset/fuzzy-ghosts-attack.md
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
Prior this fix, value `Unexpected type` was rendered.
> fix(orchestrator): results card renders boolean values properly

- workspaces/adoption-insights/.changeset/tough-paws-invent.md
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/partition.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/partition.ts
**Fixes**:
https://issues.redhat.com/browse/RHDHSUPP-222
**Description:**
Partition overlap error is caused in adoption insights fails RHDH pod from starting up successfully.
```
redhat-developer-hub-9546d5b77-8z8r6 backstage-backend 2025-05-14T16:06:37.039199203-04:00 error:
redhat-developer-hub-9546d5b77-8z8r6 backstage-backend 2025-05-14T16:06:37.039204503-04:00 CREATE TABLE IF NOT EXISTS events_2025_5
redhat-developer-hub-9546d5b77-8z8r6 backstage-backend 2025-05-14T16:06:37.039210603-04:00 PARTITION OF events
redhat-developer-hub-9546d5b77-8z8r6 backstage-backend 2025-05-14T16:06:37.039216203-04:00 FOR VALUES FROM ('2025-05-01') TO ('2025-07-01');
```
**Root cause analysis:**
Partitions were created with date ranges between 2 months instead of 1 month. This is caused by the following …
> fix(adoption-insights):  partition overlap error and auto correct the invalid partitions

- workspaces/orchestrator/plugins/orchestrator-form-api/report.api.md
- workspaces/orchestrator/plugins/orchestrator-form-api/src/DefaultFormApi.tsx
- workspaces/orchestrator/plugins/orchestrator-form-api/src/api.ts
- workspaces/orchestrator/plugins/orchestrator-form-api/src/context.ts
- workspaces/orchestrator/plugins/orchestrator-form-api/src/index.ts
- workspaces/orchestrator/plugins/orchestrator-form-react/src/components/OrchestratorFormWrapper.tsx
- workspaces/orchestrator/plugins/orchestrator-form-widgets/report.api.md
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/FormWidgetsApi.tsx
Fixes: FLPATH-2343
Contrary to the static plugins, the former way of creating a react context  lead to two instances created by two plugins at runtime when used in RHDH dynamic plugins.
> chore(orchestrator): make OrchestratorFormContext singleton in dynamic plugins

- workspaces/global-header/.changeset/grumpy-trainers-turn.md
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ProfileDropdown.test.tsx
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ProfileDropdown.tsx
Part of :  https://github.com/redhat-developer/rhdh-plugins/pull/732
Resolves: https://issues.redhat.com/browse/RHIDP-7057
Description: 
Only relying on `displayname` will not render the displayname configured by the user in `spec.profile.displayname`  or `metadata.title` property in the user entity.
The reporter who raised the concern mentioned that he wishes to see his configured display name in the global-header's profile dropdown.
So, considering that we prioritize the configured displayname, if that is not specified, we fall back to `displayname` generated by the `useProfileInfo` hook that returns user-friendly displaynames
Screenshots:
When `spec.profile.displayname` is configured
```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
name: debsmita1
title: Debsmita Santra
spec: …
```
> fix(global-header): fix global-header to prioritize 'spec.profile.displayname'

- .github/renovate-presets/base/rhdh-devdependency-presets.json
- .github/renovate-presets/base/rhdh-minor-presets.json
- .github/renovate-presets/base/rhdh-patch-presets.json
- .github/renovate-presets/workspace/rhdh-adoption-insights-presets.json
- .github/renovate-presets/workspace/rhdh-ai-presets.json
- .github/renovate-presets/workspace/rhdh-bulk-import-presets.json
- .github/renovate-presets/workspace/rhdh-global-ui-presets.json
- .github/renovate-presets/workspace/rhdh-homepage-presets.json
- .github/renovate-presets/workspace/rhdh-marketplace-presets.json
- .github/renovate-presets/workspace/rhdh-openshift-image-registry-presets.json
- .github/renovate-presets/workspace/rhdh-orchestrator-presets.json
- .github/renovate-presets/workspace/rhdh-sandbox-presets.json
- .github/renovate-presets/workspace/rhdh-theme-presets.json
- .github/renovate.json
Fixes: https://issues.redhat.com/browse/RHIDP-6050
This PR introduces a rework of the renovate config to include:
- creation of workspace specific PRs with automerge enabled for patch updates and dev dependencies.  Major updates will require dashboard approval as usual
- disabling vulnerability alerts as this causes additional memory consumption on the server which will likely cause failures.  Dependabot is currently enabled for this and works in a similar way
> chore: rework renovate configs

- workspaces/theme/.changeset/fair-ears-hang.md
- workspaces/theme/plugins/theme/src/utils/createComponents.ts
> fix(theme): support global-header above-sidebar position

- workspaces/lightspeed/.changeset/rude-ways-pump.md
- workspaces/lightspeed/plugins/lightspeed/README.md
- workspaces/lightspeed/plugins/lightspeed/config.d.ts
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/const.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/__tests__/useWelcomePrompts.test.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/useWelcomePrompts.ts
- workspaces/lightspeed/plugins/lightspeed/src/types.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/__tests__/prompt-utils.test.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/prompt-utils.ts
https://issues.redhat.com/browse/RHDHPAI-488
Sample prompts can be configured by platform engineers, three random prompts will be used by the user configured prompts and if no user prompts are configured then it will pick from the [default prompts](https://github.com/redhat-developer/rhdh-plugins/compare/main...karthikjeeyar:add-sample-prompts?expand=1#diff-ead336386fe9d8d6c984ac30ac0dceb43a688358438875f983e18812b922dc91). 
configration:    
```yaml
lightspeed:
prompts:
- title: 'Write an article'
message: Can you write an article on event driven architecture?
- title: 'Set up a Tekton pipeline for app deployment'
message: 'Can you help me automate the deployment of my application using Tekton pipelines?'
```   
Note: Prompts are picked based on the `questionValidation` setting. If …
> feat(lightspeed): add configurable sample prompts in lightspeed

- workspaces/orchestrator/plugins/orchestrator/package.json
- workspaces/orchestrator/plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx
- workspaces/orchestrator/yarn.lock
Recently we use `@monaco-editor/react` dependency instead.
> chore(orchestrator): remove redundant monaco-editor dependency

- workspaces/sandbox/packages/app/e2e-tests/app.test.ts
Add a header test to check if 'Red Hat Developer Hub' and 'Contact Red Hat Sales' links are not broken
[SANDBOX-1197](https://issues.redhat.com/browse/SANDBOX-1197)
> SANDBOX-1197: add header test for sandbox plugin

- workspaces/lightspeed/.changeset/brown-papayas-wave.md
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/components/__tests__/LightspeedChat.test.tsx
Fixes:
https://issues.redhat.com/browse/RHDHPAI-844
Clear the last opened conversation ID saved in the browser local storage
-  when there are no conversations available for the logged in user. 
-  If user deletes all their conversation manually.
Before:
Conversation ID formats are modified and it is creating conflicts.
After:
Since there are no conversations yet, we reset the browser storage too.
1. Run an older version of lightspeed (without RCS) and create a conversation.
- Option 1 : Use older commit `git checkout f406790cc5f1ed2e5de85398352152cc7f6b89e8` and run the application.
- Option 2: (Using image): Use an old image [quay.io/repository/karthik_jk/lightspeed:stable](https://quay.io/repository/karthik_jk/lightspeed)
2. after creating a conversation from step 1, kill the …
> fix(lightspeed): reset localstorage when the conversations are empty 

- .github/workflows/auto-version-bump.yml
Fixed the bash format in the prepare step for the following error:
```
Auto Version Bump
Error when evaluating 'strategy' for job 'batch-dispatch'. .github/workflows/auto-version-bump.yml (Line: 29, Col: 15): A sequence was not expected
```
> fix: auto-version-bump prepare step

- workspaces/bulk-import/.changeset/selfish-brooms-heal.md
- workspaces/bulk-import/plugins/bulk-import/package.json
- workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.tsx
- workspaces/bulk-import/plugins/bulk-import/src/hooks/useRepositories.ts
- workspaces/bulk-import/yarn.lock
This PR focuses on improving the performance and efficiency of the Bulk Import page by reducing unnecessary API calls and improving user experience.
- When switching between the **Organizations** and **Repositories** tabs, API calls for both tabs were being made — even if only one was actively in view.
- Unintended API requests were triggered by generic screen clicks.
- Pagination controls triggered API calls even when the page number or page size didn't change.
- Search input was missing **debounce**, resulting in multiple API requests for each keystroke (e.g., typing “test” sent 4 requests).
Fixing https://issues.redhat.com/browse/RHIDP-7658
1. **Tab Switching Optimization**  
- Ensured that only the active tab triggers its respective API call.
2. **Reduced Redundant Triggers**  
- …
> fix(bulk-import): removing extra apis call

- workspaces/ai-integrations/plugins/catalog-backend-module-model-catalog/src/processors/RHDHRHOAIReaderProcessor.test.ts
This PR adds test coverage for the Model Catalog reader processor. 
I utilized watsonx Code Assistant to generate a skeleton of the structure for reader processor tests, then manually tweaked to resolve errors in the test output and ensure full test coverage for functionality specific to the model catalog processor.
> chore(ai-integration): add tests for the model catalog reader processor

- workspaces/lightspeed/.changeset/orange-spiders-speak.md
- workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/fileUpload.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/testHelper.ts
- workspaces/lightspeed/plugins/lightspeed/package.json
- workspaces/lightspeed/plugins/lightspeed/src/components/AttachmentContext.tsx
- workspaces/lightspeed/plugins/lightspeed/src/components/FilePreview.tsx
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/components/__tests__/LightspeedChat.test.tsx
- workspaces/lightspeed/plugins/lightspeed/src/types.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/__tests__/attachment-utils.test.ts
- workspaces/lightspeed/plugins/lightspeed/src/utils/attachment-utils.ts
- workspaces/lightspeed/yarn.lock
https://issues.redhat.com/browse/RHDHPAI-850
While uploading attachments in lightspeed, users will now only see `.yaml`, `.json`,`.txt` and `.xml` files being enabled for them to choose from. 
| Before fix   | with this PR changes |
| -------- | ------- |
|![image](https://github.com/user-attachments/assets/d23b1f5d-1443-4afd-b0f2-0e6052c6a036)  | ![image](https://github.com/user-attachments/assets/e24dbd50-1402-4317-ad25-350622ff4a08) |
---
> fix(lightspeeed): Enable only supported file types while uploading attachments

- workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/fileUpload.ts
📝 **PR Description:**
This PR introduces an automated Playwright test for verifying the application's behavior when multiple files are uploaded simultaneously.
✅ **Changes:**
* Added a test that uploads two files using the `uploadFile` utility.
* Asserted the presence of a danger alert with:
* Heading: **"Danger alert: File upload"**
* Message: **"Uploaded more than one file."**
* Verified the alert is visible when multiple files are uploaded.
* Clicked the close button on the alert and validated it is no longer visible.
* Introduced a `verifyAlertPopup` helper function to check alert visibility or hidden state based on expectations.
📎 **Trace Attachment:**
* A trace file is attached to this PR for inspection and debugging.
🛠️ **To view the trace:**
* Run `npx playwright show-trace …
> Add test for multiple file upload

- workspaces/marketplace/.changeset/calm-dolls-laugh.md
- workspaces/marketplace/plugins/marketplace/src/components/ActionsMenu.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.test.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx
Resolves:
https://issues.redhat.com/browse/RHIDP-7244
_**The enable/disable plugin feature is disabled till we have the API (https://github.com/redhat-developer/rhdh-plugins/pull/921). To test the PR, manually set the if condition in line no 274 to true in the file MarketplacePluginContent.tsx**_
> feat(extensions): add actions button to enable/disable plugin

- workspaces/orchestrator/.changeset/fresh-gorillas-know.md
- workspaces/orchestrator/docs/orchestratorFormWidgets.md
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/applySelector.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx
Adding `fetch:response:value` selector for the `SchemaUpdater` widget which can be optionally used to pick-up (narrow) input data for the `SchemaUpdater` in the cases of complex responses are received from the endpoint.
The requested data structure for the `SchemaUpdater` stays untouched, just the endpoint response does not need to be tightly coupled with the format expected by the `SchemaUpdater`.
> feat(orchestrator): add support for selectors in SchemaUpdater

- workspaces/orchestrator/.changeset/lucky-boxes-float.md
- workspaces/orchestrator/docs/orchestratorFormWidgets.md
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/applySelector.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveMultiSelect.tsx
Adding "fetch:response:mandatory" selector for the `ActiveMultiSelect` widget which can be used to pick-up an array of strings as default but unselectable items of the list.
~~This will need rebase.~~ Based on:
Example in: https://github.com/rhdhorchestrator/orchestrator-demo/pull/39
---
> feat(orchestrator): add 'fetch:response:mandatory selector for ActiveMultiSelect

- workspaces/orchestrator/plugins/orchestrator-backend/src/service/router.ts
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInputs.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePageContent.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowResult.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
1. No space between the about fields in instance page results and details
2. No scrollbar in inputs and progress cards
3. Unified L & F or workflow status and instance status
Includes bug fix found while testing - when default input is false, it didn't show in the inputs card
Before
After
resolves:
[FLPATH-2411](https://issues.redhat.com/browse/FLPATH-2411)
[FLPATH-2414](https://issues.redhat.com/browse/FLPATH-2414)
> fix(orchestrator): multiple visibility issues

- workspaces/lightspeed/.changeset/blue-eagles-confess.md
- workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts
- workspaces/lightspeed/plugins/lightspeed-backend/README.md
- workspaces/lightspeed/plugins/lightspeed-backend/src/service/router.ts
- workspaces/lightspeed/plugins/lightspeed-common/report.api.md
- workspaces/lightspeed/plugins/lightspeed-common/src/permissions.ts
- workspaces/lightspeed/plugins/lightspeed/README.md
- workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx
- workspaces/lightspeed/plugins/lightspeed/src/components/PermissionRequiredState.tsx
- workspaces/lightspeed/plugins/lightspeed/src/hooks/useLightspeedDeletePermission.ts
- workspaces/lightspeed/plugins/lightspeed/src/hooks/useLightspeedViewPermission.ts
- Renamed placeholder text in chat history sidebar.
- Renamed permissions to align with the updated naming convention:
- `lightspeed.conversations.read` → `lightspeed.chat.read`
- `lightspeed.conversations.create` → `lightspeed.chat.create`
- `lightspeed.conversations.delete` → `lightspeed.chat.delete`
**Missing permissions alert:**
---
**Chatbot:**
> fix(lightspeed): rename conversations to chat in lightspeed plugins

- workspaces/orchestrator/.changeset/shiny-glasses-draw.md
- workspaces/orchestrator/docs/orchestratorFormWidgets.md
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.test.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useFetch.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useFetchAndEvaluate.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useGetExtraErrors.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useRequestInit.ts
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useTemplateUnitEvaluator.ts
Fixes: FLPATH-2432
The templates can be evaluated to primitive values (string, number), complex (nested) objects or arrays (items can be primitive values, objects or arrays).
> feat(orchestrator): template units can be evaluated to complex objects and arrays

- workspaces/global-header/.changeset/soft-nails-boil.md
- workspaces/global-header/plugins/global-header/app-config.dynamic.yaml
- workspaces/global-header/plugins/global-header/src/defaultMountPoints/defaultMountPoints.tsx
This PR updates the default mount points and dynamic plugin config to include starred dropdown and application launcher with quick links.
> chore(global-header): update default mount points with quick links

- workspaces/sandbox/plugins/sandbox/src/components/Modals/AnsibleLaunchInfoModal.tsx
- workspaces/sandbox/plugins/sandbox/src/components/Modals/__tests__/AnsibleLaunchInfoModal.test.tsx
This is for removing the close button from the Ansible Info modal.
See: https://redhat-internal.slack.com/archives/C07UWTB1BPB/p1750885726468589?thread_ts=1749060005.628409&cid=C07UWTB1BPB
> fix(sandbox): remove close button from ansible modal

- workspaces/adoption-insights/.changeset/sad-doodles-bake.md
- workspaces/adoption-insights/plugins/adoption-insights-backend/package.json
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.ts
- workspaces/adoption-insights/yarn.lock
I changed the code for the adoption insights partitions to ensure new dates are created in the UTC timezone. (also by changing to Luxon, we can use toIsoDate() instead of slicing the result)
Reason for this was that my local run of backstage for some reason takes timezones into account in this script. That results in the partition to be created for the timerange `FOR VALUES FROM ('2025-05-31 00:00:00+00') TO ('2025-06-30 00:00:00+00')` which fails today (30th of June) because the value is outside of the range, while a new partition is not yet created.
Example from the browser:
```
new Date(2025,5,1)
Date Sun Jun 01 2025 00:00:00 GMT+0200 (Central European Summer Time)
new Date(2025,5,1).toISOString()
"2025-05-31T22:00:00.000Z" 
```
Unfortunately, I could not create a test to verify the …
> fix: ensure partition start and end date are created in UTC timezone

- workspaces/orchestrator/README.md
1. Added doc on prerequisite tools for yarn install to succeed
2. Included missing enable in rhdh link
> docs(orchestrator): two readme fixes

- workspaces/adoption-insights/.changeset/tame-hornets-rescue.md
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/SqliteAdapter.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/date.test.ts
- workspaces/adoption-insights/plugins/adoption-insights-backend/src/utils/date.ts
https://issues.redhat.com/browse/RHDHPAI-941
Previously, timezone offsets were derived from the system environment, causing inconsistent aggregation results between local and containerized environments (e.g., UTC in Podman/Kubernetes Pod vs IST locally) in `better-sqlite3` settings.
This PR adds a fix by passing the user timezone to calculate the timezone offset rather than relying on the backend system environment's timezone.
**Before:**
Shows the time in UTC:
_Note: Follow Step 1 and Step 2 from the "How to test" section to reproduce this issue._
**After:**
Shows the time in user's timezone (IST in my case):
**How to test:**
1. use latest RHDH image `quay.io/rhdh-community/rhdh:next` with adoption insights.
2. use `better-sqlite3` database client in app-config.yaml
```yaml
backend …
```
> fix(adoption-insights): fix timezone offset inconsistency in sqlite grouping queries

- workspaces/marketplace/.changeset/strong-gorillas-bow.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.test.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/pages/MarketplacePluginInstallPage.tsx
- workspaces/marketplace/plugins/marketplace/src/utils.ts
https://issues.redhat.com/browse/RHIDP-8121
Fixes the issues in the PR https://github.com/redhat-developer/rhdh-plugins/pull/1111
In the Edit flow on the plugin configuration page, it shows "Edit instructions" instead of "Installation instructions"
In the edit flow, when the plugin configuration is updated, the notification alert shows plugin updated instead of plugin installed
When the user has only read access, it shows the View button
**Test setup**
`app-config.local.yaml`
```
permission:
enabled: true
rbac:
pluginsWithPermission:
- extensions
- catalog
- permission
admin:
users:
- name: user:default/<your-username>
```
Create an RBAC role with your desired extension permissions
Note: To test on RHDH-local follow this [doc](https://docs.google.com/document/d/1_kLj5-R3Rg2zDd89mE3BPZLavMs …
> fix(extensions): hide actions menu in view only mode

- workspaces/marketplace/.changeset/hip-pots-wink.md
- workspaces/marketplace/plugins/marketplace-backend/src/installation/FileInstallationStorage.test.ts
- workspaces/marketplace/plugins/marketplace-backend/src/installation/FileInstallationStorage.ts
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1880
https://github.com/user-attachments/assets/7ad9c256-2db7-473d-86c7-3e8b16741de1
Note: Plugin install status is for a little while set still to disabled, this is because processor hasn't yet started processing this entity and updating its status.
> fix(extensions): Set disabled for all plugin packages

- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
After [PR](https://github.com/redhat-developer/rhdh-plugins/pull/1089) that removed workflow category, the workflow run details card became warped. This PR fixes it according to updated [figma](https://www.figma.com/design/XjdTCb4vDQ7L4Jz1TdHKGq/Workflow-Orchestrator?node-id=4896-5438&t=Cq06pOVqH36LEroJ-0). 
Before:
After:
> fix(orchestrator): fix warped details card

- workspaces/lightspeed/packages/app/e2e-tests/app.test.ts
- workspaces/lightspeed/packages/app/e2e-tests/fixtures/responses.ts
- workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/devMode.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/login.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/sidebar.ts
- workspaces/lightspeed/packages/app/e2e-tests/utils/testHelper.ts
Gives the lightspeed playwright tests the option to run either in dev mode, or using live RHDH instance
> test(lightspeed): make lightspeed tests runnable on live data

- workspaces/marketplace/.changeset/proud-apes-cross.md
- workspaces/marketplace/plugins/marketplace-backend/src/errors/InstallationInitError.ts
- workspaces/marketplace/plugins/marketplace-backend/src/installation/InstallationDataService.test.ts
- workspaces/marketplace/plugins/marketplace-backend/src/installation/InstallationDataService.ts
- workspaces/marketplace/plugins/marketplace-backend/src/router.test.ts
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/utils.ts
Restricts access to configuration endpoints in production.
Fixes https://issues.redhat.com/browse/RHDHBUGS-1888
https://github.com/user-attachments/assets/5f7d202f-56da-46be-ba77-67b25e549d93
rhdh-local
1. Build and push marketplace and marketplace backend plugin
2. change `compose`:
```
rhdh:
...    
environment:
NODE_OPTIONS: "--inspect=0.0.0.0:9229"
NODE_ENV: "production"
```
> fix(extensions): restrict access to configuration endpoints in production

- workspaces/openshift-image-registry/.changeset/tame-carrots-behave.md
- workspaces/openshift-image-registry/plugins/openshift-image-registry/package.json
- workspaces/openshift-image-registry/plugins/openshift-image-registry/src/hooks/useAllNsImageStreams.ts
- workspaces/openshift-image-registry/plugins/openshift-image-registry/src/utils.test.ts
- workspaces/openshift-image-registry/plugins/openshift-image-registry/src/utils.ts
- workspaces/openshift-image-registry/yarn.lock
This pull request refactors the `formatDate` utility to use `luxon` instead of `date-fns`. This work is part of the larger effort to remove dependencies on the `@janus-idp/shared-react` package.
This change aligns the utility with **[ADR012: Adopt Luxon as a standardized date and time library](https://backstage.io/docs/architecture-decisions/adrs-adr012/)**, which aims to standardize date/time handling across the codebase for better consistency and maintainability.
The new implementation maintains the existing function signature and behavior:
* It correctly handles `string`, `number` (Unix timestamp), and `Date` object inputs.
* It continues to return `'N/A'` for `null`, `undefined`, or invalid date inputs.
* The output format string has been updated to the `luxon` equivalent to ensure …
> feat(openshift-image-registry): aligning formatDate utility with ADR012 using Luxon

- workspaces/marketplace/.changeset/two-foxes-run.md
- workspaces/marketplace/examples/packages/backstage-community-plugin-quay.yaml
- workspaces/marketplace/json-schema/packages.json
- workspaces/marketplace/plugins/marketplace-backend/src/validation/configValidation.test.ts
- workspaces/marketplace/plugins/marketplace-backend/src/validation/configValidation.ts
- workspaces/marketplace/plugins/marketplace-common/report.api.md
- workspaces/marketplace/plugins/marketplace-common/src/types/MarketplacePackage.ts
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
Plugins from NPM registry and packaged as a TGZ can be installed by introducing `spec.integrity` field for Marketplace package
[Docs about possible installations of third party plugins](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/installing_and_viewing_plugins_in_red_hat_developer_hub/assembly-third-party-plugins#assembly-package-publish-third-party-dynamic-plugin)
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1882
https://github.com/user-attachments/assets/29427d49-5229-4909-a4dc-99d750241e70
You can use quay entity I updated in this PR with integrity (add to catalog locations both plugin and package, you need to add via url or simpler, add the entities under app-config/marketplace/all.yaml and reference as `target: …
> fix(extensions): introduce package integrity

- workspaces/homepage/.changeset/good-squids-check.md
- workspaces/homepage/plugins/dynamic-home-page/src/components/HomePage.tsx
This PR fixes an issue where the homepage title always displayed **"Welcome back!"**, ignoring the value configured through  `app-config.yaml`.
---
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1903
The homepage title configuration is being ignored due to a `title="Welcome back!"` prop in the HomePage component. This prevents users from customizing the homepage title  configured through  `app-config.yaml`, causing it to always default to "Welcome back!" regardless of the configured value.
The explicit `title="Welcome back!"` prop in HomePage.tsx overrides any title configuration passed  via configuration, breaking the customization functionality. This got  introduced as part of [PR #745](https://github.com/redhat-developer/rhdh-plugins/pull/745)
For testing 
1. Take this PR change in …
> fix(homepage): fixing homepage title not respecting value from app-config.yaml

- workspaces/marketplace/.changeset/friendly-pugs-applaud.md
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/DynamicPackageInstallStatusProcessor.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/DynamicPackageInstallStatusProcessor.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/LocalPackageInstallStatusProcessor.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/PluginInstallStatusProcessor.test.ts
- workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/PluginInstallStatusProcessor.ts
Clear processors logging to include entity name of processed entity. Switch to debug for now as some of our default entities are missing needed specs and those cases were not previously logged.
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1905
> fix(extensions): clear processors logging

- workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/PhoneNumberStep.tsx
- workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/__tests__/PhoneNumberStep.test.tsx
when you edit the phone number the phone field has the country code in it twice.
See: https://redhat-internal.slack.com/archives/C085PFGDLGY/p1752845648400689?thread_ts=1752754021.468099&cid=C085PFGDLGY
Jira: https://issues.redhat.com/browse/SANDBOX-1365
> fix(sandbox): phone number should not have duplicated country code

- workspaces/marketplace/.changeset/good-colts-exist.md
- workspaces/marketplace/plugins/marketplace-common/report.api.md
- workspaces/marketplace/plugins/marketplace-common/src/types/MarketplacePackage.ts
- workspaces/marketplace/plugins/marketplace/src/components/CodeEditorCard.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePackageInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/TabPanel.tsx
- workspaces/marketplace/plugins/marketplace/src/utils.test.ts
- workspaces/marketplace/plugins/marketplace/src/utils.ts
Fixes:
https://issues.redhat.com/browse/RHDHBUGS-1874
- With this fix, the Examples tab will load all the appConfigExamples for all the packages associated to the plugin. It adds the package title with the default configuration below.
- Not displaying the Examples tab if no appConfigExamples are present.
- Removed duplicated code and created reusable components
https://github.com/user-attachments/assets/e0a05e1d-0e87-4b12-9d41-51fbe744a90a
**Before**
https://drive.google.com/file/d/1r_i4j9AM8jRCb8mZdux6jmWfGbWEy6nG/view
**After**
> fix(extensions): load all the package configurations

- workspaces/marketplace/.changeset/fast-carrots-behave.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
- workspaces/marketplace/plugins/marketplace/src/components/TabPanel.tsx
**Resolves**
https://issues.redhat.com/browse/RHDHBUGS-719
Before
After
> fix(extensions): hide tab layout when there's only one tab left

- workspaces/ai-integrations/.changeset/thirty-stars-wear.md
- workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend/package.json
- workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend/src/plugin.test.ts
- workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend/src/plugin.ts
- workspaces/ai-integrations/yarn.lock
removes the temporary duplicate config code from the url reader dropped by https://github.com/redhat-developer/rhdh-plugins/pull/1256
- [/ ] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [n/a ] Added or Updated documentation
- [/ ] Tests for new functionality and regression tests for bug fixes
- [ n/a] Screenshots attached (for UI changes)
> RHDHPAI-682: remove temporary duplicate model catalog bridge config code from url reader

- workspaces/theme/Makefile
`janus-idp/cli` is being deprecated; plugins should now use https://github.com/redhat-developer/rhdh-cli
fixes https://issues.redhat.com/browse/RHIDP-8531
> chore(theme): makefile - use rhdh-cli instead of janus-cli

- workspaces/marketplace/Makefile
`janus-idp/cli` is being deprecated; plugins should now use https://github.com/redhat-developer/rhdh-cli
fixes https://issues.redhat.com/browse/RHIDP-8531
> chore(marketplace): makefile - use rhdh-cli instead of janus-cli

- workspaces/openshift-image-registry/.changeset/fair-bikes-mate.md
- workspaces/openshift-image-registry/plugins/openshift-image-registry/package.json
- workspaces/openshift-image-registry/yarn.lock
`janus-idp/cli` is being deprecated in favor of https://github.com/redhat-developer/rhdh-cli
`export-dynamic` script is no longer necessary, and it is encouraged not to modify plugins to adapt dynamic plugins.
Plugins can be exported as dynamic either by leveraging [overlay repository](https://github.com/redhat-developer/rhdh-plugin-export-overlays)  or simply by executing `npx @red-hat-developer-hub/cli`
> chore(openshift-image-registry): remove janus-idp/cli and export-dynamic

- workspaces/global-floating-action-button/.changeset/fresh-tools-walk.md
- workspaces/global-floating-action-button/plugins/application-listener-test/package.json
- workspaces/global-floating-action-button/plugins/application-provider-test/package.json
- workspaces/global-floating-action-button/yarn.lock
`janus-idp/cli` is being deprecated in favor of https://github.com/redhat-developer/rhdh-cli
`export-dynamic` script is no longer necessary, and it is encouraged not to modify plugins to adapt dynamic plugins.
Plugins can be exported as dynamic either by leveraging [overlay repository](https://github.com/redhat-developer/rhdh-plugin-export-overlays)  or simply by executing `npx @red-hat-developer-hub/cli` 
fixes https://issues.redhat.com/browse/RHIDP-8531
> chore(global-floating-action-button): remove janus-idp/cli and export-dynamic

- workspaces/adoption-insights/.changeset/gentle-radios-tease.md
- workspaces/adoption-insights/plugins/adoption-insights/src/components/ActiveUsers/ActiveUsers.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/ActiveUsers/CustomLegend.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/CatalogEntities/CatalogEntities.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Plugins/Plugins.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Plugins/__tests__/Plugins.test.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Searches/Searches.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Techdocs/Techdocs.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Templates/Templates.tsx
- workspaces/adoption-insights/plugins/adoption-insights/src/components/Users/Users.tsx
- Removed empty space when empty message - [RHDHBUGS-1943](https://issues.redhat.com/browse/RHDHBUGS-1943).
- Show proper indication in "Top 3 plugins" card when no trends exist - [RHDHBUGS-1965](https://issues.redhat.com/browse/RHDHBUGS-1965).
- Display trend percentage in top plugins chart on initial load - [RHDHBUGS-1956](https://issues.redhat.com/browse/RHDHBUGS-1956).
- Align legend correctly in "Active users" card - [RHDHBUGS-1962](https://issues.redhat.com/browse/RHDHBUGS-1962).
Improves overall UI consistency and readability in the Adoption Insights dashboard.
Screenshots
> fix(adoption-insights): align legends, show trends, and remove empty space

- workspaces/quickstart/app-config.yaml
- workspaces/quickstart/plugins/quickstart/config.d.ts
- workspaces/quickstart/plugins/quickstart/src/components/Quickstart.test.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartContent/QuickstartContent.test.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartContent/QuickstartContent.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartContent/QuickstartItemIcon.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartDrawer.test.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartDrawer.tsx
- workspaces/quickstart/plugins/quickstart/src/components/mockData.ts
- workspaces/quickstart/plugins/quickstart/src/types.ts
- workspaces/quickstart/plugins/quickstart/src/utils/filterQuickstartItems.test.ts
- workspaces/quickstart/plugins/quickstart/src/utils/filterQuickstartItems.ts
- workspaces/quickstart/plugins/quickstart/src/utils/index.ts
For [RHIDP-8455](https://issues.redhat.com/browse/RHIDP-8455).
This PR adds role-based filtering for Quickstart items, so only steps relevant to the current user’s role (admin, developer, etc.) are shown in the UI. It updates config, data, and UI to support this, improves empty state messaging, adds new icons, and expands test coverage for these changes.
Sections for "developer" role
When no content available for current role
> feat(quickstart): added support to role-based quickstart

- workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend/src/plugin.ts
this will allow backstage's leveraging of http 304's in order to avoid re-building techdocs and not surface the 304 as a error
> fix: catalog-techdoc-url-reader should hand unmodified http rc

- workspaces/orchestrator/.changeset/mean-cherries-yell.md
- workspaces/orchestrator/plugins/orchestrator/package.json
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/ServerlessWorkflowEditor.tsx
- workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsTabContent.tsx
- workspaces/orchestrator/yarn.lock
Fixes FLPATH-1327 by replacing kie-tools viewer by CodeSnippet.
We are loosing the read-only diagram but
- resolving CSP issues
- significantly reducing the bundle size
- leveraging well-tested and supported component
- avoiding complicated integration of a 3rd party component
Considering the component is shown to administrators only, such simplification should be acceptable.
---
This PR would obsolete
- https://github.com/redhat-developer/rhdh-plugins/pull/1381
- https://github.com/redhat-developer/rhdh-plugins/pull/1374
> fix(orchestrator): use CodeSnippet instead of kie-tools editor

- workspaces/global-header/.changeset/fix-dropdown-empty-state-border-radius.md
- workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/DropdownEmptyState.tsx
**Fixes:**
https://issues.redhat.com/browse/RHDHBUGS-1921
Fixed dropdown empty state corners by removing the border line
> fix(global-header): Global header dropdown empty state corners looks off

- .github/CODEOWNERS
This replaces the long list of individuals in the code owners file with the rhdh-plugins or rhdh-ui team group.
For the UI team, I've added the point of contact to all workspaces.
I kept additional members from other teams, of course.
/cc @kadel @redhat-developer/rhdh-ui
> chore(repo): update ownersfile

- workspaces/marketplace/.changeset/plugin-card-ux-improvements.md
- workspaces/marketplace/plugins/marketplace/src/components/CategoryLinkButton.test.tsx
- workspaces/marketplace/plugins/marketplace/src/components/CategoryLinkButton.tsx
- workspaces/marketplace/plugins/marketplace/src/components/PluginCard.test.tsx
- workspaces/marketplace/plugins/marketplace/src/components/PluginCard.tsx
- workspaces/marketplace/plugins/marketplace/src/utils.test.ts
- workspaces/marketplace/plugins/marketplace/src/utils.ts
https://issues.redhat.com/browse/RHIDP-8300
- Added visual install status indicators (Installed, Disabled) on plugin cards
- Enhanced hover interaction on category tags with visual feedback
- Implemented long tag name truncation with ellipsis and full-name tooltips for better layout
- Fixed alignment for plugin cards without tags to maintain consistent layout
- Ensured plugin description text always starts at the same horizontal point for better readability
> RHIDP-8300: Plugin card UX improvements

- workspaces/quickstart/.changeset/add-quickstart-i18n-support.md
- workspaces/quickstart/packages/app/src/App.test.tsx
- workspaces/quickstart/packages/app/src/App.tsx
- workspaces/quickstart/plugins/quickstart/dev/index.tsx
- workspaces/quickstart/plugins/quickstart/report.api.md
- workspaces/quickstart/plugins/quickstart/src/alpha.ts
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartButton/QuickstartButton.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartContent/QuickstartContent.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartContent/QuickstartItem.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartFooter.tsx
- workspaces/quickstart/plugins/quickstart/src/components/QuickstartHeader.tsx
- workspaces/quickstart/plugins/quickstart/src/components/Trans.test.tsx
- workspaces/quickstart/plugins/quickstart/src/components/Trans.tsx
- workspaces/quickstart/plugins/quickstart/src/hooks/useTranslation.ts
- workspaces/quickstart/plugins/quickstart/src/plugin.ts
- workspaces/quickstart/plugins/quickstart/src/setupTests.ts
- workspaces/quickstart/plugins/quickstart/src/test-utils/mockTranslations.ts
- workspaces/quickstart/plugins/quickstart/src/translations/de.ts
- workspaces/quickstart/plugins/quickstart/src/translations/es.ts
- workspaces/quickstart/plugins/quickstart/src/translations/fr.ts
- workspaces/quickstart/plugins/quickstart/src/translations/index.ts
- workspaces/quickstart/plugins/quickstart/src/translations/ref.ts
https://issues.redhat.com/browse/RHIDP-8745
Added internationalization (i18n) support to QuickStart. The plugin now supports multiple languages with proper fallbacks and maintains all existing functionality. 
- Multi-language support: English (default), German, French, and Spanish
**Languages added:**
1. 🇫🇷 French (fr)
2. 🇩🇪 German (de)
3. 🇪🇸 Spanish (es)
4. 🇺🇸 English (en) - default
--------
--------
--------
--------
--------
> feat(i18n): Add translation support for QuickStart

- .eslintrc.cjs
- workspaces/translations/README.md
- workspaces/translations/plugins/translations/src/apis/I18nextTranslationApi.ts
- workspaces/translations/plugins/translations/src/apis/TranslationRef.ts
- workspaces/translations/plugins/translations/src/apis/TranslationResource.ts
- workspaces/translations/plugins/translations/src/apis/index.ts
I've modified the eslint rule that has overridden the origin authors of (opensource) code that I've copied from the backstage project. But I like to honor the origin work.
I've added also a README to the new translations workspace to make clear that this is in best case an interim solution and that we like to bring this features to Backstage Core or Backstage Community Plugins.
> chore(translations): fix copyright author

- workspaces/marketplace/.changeset/thirty-bananas-buy.md
- workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.tsx
Resolves: https://issues.redhat.com/browse/RHDHBUGS-1972
Keeping the plugin installation info alert bar closed by default
> fix(extensions): keep info bar closed by default

- workspaces/scorecard/plugins/scorecard-backend-module-github/src/github/GitHubClient.test.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/github/GithubClient.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/github/constants.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/github/utils.test.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/github/utils.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/metricProviders/GithubOpenPRsProvider.test.ts
- workspaces/scorecard/plugins/scorecard-backend-module-github/src/metricProviders/GithubOpenPRsProvider.ts
Make Github app integration work for scorecard.
Fixes https://issues.redhat.com/browse/RHDHBUGS-2078
Update `github-scorecard-only.yaml`: github.com/project-slug and backstage.io/source-location to some repo that is in the organization/user for which you have installed Github app.
1. First try out that your token integration still works:
```
integrations:
github:
- host: github.com
token: XXX
```
2. Try out Github app:
```
integrations:
github:
- host: github.com
apps:
- appId: XXX
clientId: XXX
clientSecret: XXX
webhookSecret: XXX
privateKey: |
XXX
```
Note: This uses the first available integration for a host, currently there is no easy way to switch to a different one if there are multiple intergrations for the same host and the first matched one doesn't have access to concrete repo. …
> fix(scorecard): Fix github app integration

- workspaces/scorecard/app-config.yaml
- workspaces/scorecard/packages/app/e2e-tests/pages/ScorecardPage.ts
- workspaces/scorecard/plugins/scorecard/report-alpha.api.md
- workspaces/scorecard/plugins/scorecard/src/components/Common/NoScorecardsState.tsx
- workspaces/scorecard/plugins/scorecard/src/components/Common/PermissionRequiredState.tsx
- workspaces/scorecard/plugins/scorecard/src/components/Common/__tests__/NoScorecardsState.test.tsx
- workspaces/scorecard/plugins/scorecard/src/components/Common/__tests__/PermissionRequiredState.test.tsx
- workspaces/scorecard/plugins/scorecard/src/translations/de.ts
- workspaces/scorecard/plugins/scorecard/src/translations/es.ts
- workspaces/scorecard/plugins/scorecard/src/translations/fr.ts
- workspaces/scorecard/plugins/scorecard/src/translations/ref.ts
Description
- Empty state component CTA now it linking to app.support.url or RHDH Documentation
- Removed hardcoded colors in Empty state component
- Added translations for Permission required component
- Updated unit test
https://github.com/user-attachments/assets/91ee820a-8f6b-48a9-a12b-95642306ccdc
> fix(scorecard): update empty state component and add translations to permission required state

- workspaces/orchestrator/.changeset/two-balloons-happen.md
- workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveDropdown.tsx
Fix ActiveDropdown for long lists.
Before (video):
https://github.com/user-attachments/assets/de3eb501-3b48-4e5d-a161-e5e1a5296ec3
After:
https://github.com/user-attachments/assets/5798f8af-3569-481e-9166-b8c05b0b1586
> fix(orchestrator): Shorten ActiveDropdown list of options

- workspaces/orchestrator/.changeset/blue-clouds-grin.md
- workspaces/orchestrator/plugins/orchestrator/src/hooks/useOrchestratorAuth.ts
Jira: FLPATH-2361
With this patch, the AuthRequester widget can reference statically added non-core auth apis (not well-names like GitHub, not provided by a plugin).
Example, the RHDH OIDC API: https://github.com/redhat-developer/rhdh/blob/main/packages/app/src/api/AuthApiRefs.ts#L18
Workflow data input schema example:
```
"authSetup": {
"type": "string",
"ui:widget": "AuthRequester",
"ui:props": {
"authTokenDescriptors": [
{
"provider": "oidc",
"customProviderApiId": "internal.auth.oidc",
"tokenType": "oauth"
}
]}
}
```
> fix(orchestrator): let AuthRequester reference static non-standard auth apis

- workspaces/homepage/.changeset/loud-weeks-tie.md
- workspaces/homepage/packages/app/src/App.tsx
- workspaces/homepage/plugins/dynamic-home-page/report.api.md
- workspaces/homepage/plugins/dynamic-home-page/src/components/QuickAccessCard.tsx
- workspaces/homepage/plugins/dynamic-home-page/src/components/QuickAccessIcon.tsx
- workspaces/homepage/plugins/dynamic-home-page/src/defaults.ts
**Resolves:**
https://issues.redhat.com/browse/RHIDP-9035
The PR updates the current QuickAccess card icon rendering logic to support `<svg>..</svg>`, `Backstage system icon`, along with `image url` and `relative path`
**Test setup:**
Update `app-config.yaml` to add proxy:
```
proxy:
endpoints:
'/developer-hub':
target: https://raw.githubusercontent.com/ # i.e https://raw.githubusercontent.com/
pathRewrite:
'^/api/proxy/developer-hub': /debsmita1/test-homepage/refs/heads/main/data-homepage.json # i.e /redhat-developer/rhdh/main/packages/app/public/homepage/data.json
changeOrigin: true
secure: true
```
PS: I have the `calendar.svg` icon downloaded and saved under `packages/app/public`
**Screenshots:**
> feat(homepage): update quickaccess card icon rendering logic

- workspaces/bulk-import/.changeset/lemon-cherries-cross.md
- workspaces/bulk-import/package.json
- workspaces/bulk-import/plugins/bulk-import-backend/src/helpers/utils.ts
This allows in the `app-config.yaml`:
```yaml
bulkImport:
importAPI: scaffolder
importTemplate: create-pr-with-catalog-info
```
instead of
```yaml
bulkImport:
importAPI: scaffolder
importTemplate: template:default/create-pr-with-catalog-info
```
Other namespaces are still possible of course.
> fix(bulk-import): automatically select templates for bulkImport.importTemplate configuration

- .sonarcloud.properties
- workspaces/bulk-import/.changeset/silver-coins-tie.md
- workspaces/bulk-import/packages/backend/package.json
- workspaces/bulk-import/packages/backend/src/index.ts
- workspaces/bulk-import/plugins/bulk-import-backend/package.json
- workspaces/bulk-import/plugins/bulk-import-backend/src/github/GithubAppManager.test.ts
- workspaces/bulk-import/plugins/bulk-import-backend/src/service/handlers/import/execute-template.ts
- workspaces/bulk-import/yarn.lock
Fixes https://issues.redhat.com/browse/RHDHBUGS-2110
- Replace @ai-zen/node-fetch-event-source with maintained and Backstage dependency @microsoft/fetch-event-source
- Removed unused dependency @roadiehq/scaffolder-backend-module-utils
- Excl. packages/app and packages/backend from sonarcloud issues
Tested it locally and works fine with the included test template!
> fix(bulk-import): use maintained fetch-event-source dependency and dropped unused scaffolder-backend-module-utils

- workspaces/bulk-import/.changeset/silly-donuts-refuse.md
- workspaces/bulk-import/packages/app/src/App.tsx
- workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx
- workspaces/bulk-import/plugins/bulk-import/src/components/BulkImportPage.tsx
- workspaces/bulk-import/plugins/bulk-import/src/components/Router.tsx
Fixes: https://issues.redhat.com/browse/RHDHBUGS-2108
Before it was necessary to have a QueryClient in the app which would not work in rhdh.
I saw that two other "pages" has their own QueryClient instance and it was "missed" on the new `TasksPage`. Instead of adding it there I removed all instances and added one around all pages in the `Router` component.
Yes, the instance is now shared also if a user leave the bulk import and opens it again. For me, this is a feature that the second time some cached (and automatically refetched!) result was displayed.
> fix(bulk-import): use a single react-query QueryClient instance for all pages and remove the need to have one in the app
