redhat-developer/rhdh-plugins

workspaces/openshift-image-registry/.changeset/tough-pugs-hide.md, workspaces/openshift-image-registry/plugins/openshift-image-registry/package.json, workspaces/openshift-image-registry/plugins/openshift-image-registry/turbo.json, workspaces/openshift-image-registry/yarn.lock
=> chore: rebase openshift-image-registry with lastest changes from janus-idp/backstage-plugins

workspaces/bulk-import/.changeset/lemon-kids-unite.md, workspaces/bulk-import/plugins/bulk-import-backend/package.json, workspaces/bulk-import/plugins/bulk-import-common/package.json, workspaces/bulk-import/plugins/bulk-import/package.json, workspaces/bulk-import/yarn.lock
=> rebase with latest changes from janus

.github/CODEOWNERS
Added codeowners for existing (bulk-import and openshift-image-registry) and for the workspaces I like to create:
I'm 100% fine if you want add someone else to bulk-import (later)
=> chore(repo): add codeowners for new workspaces

.github/CODEOWNERS
=> Update CODEOWNERS to add Kim and Kashish

workspaces/bulk-import/.changeset/config.json, workspaces/marketplace/.changeset/config.json, workspaces/openshift-image-registry/.changeset/config.json, workspaces/repo-tools/packages/cli/src/lib/workspaces/.changeset/config.json, workspaces/theme/.changeset/config.json
Align rhdh-plugins changeset config with upstream configs
See also https://github.com/backstage/community-plugins/pull/1510
=> chore(ci): ignore private repositories (esp. backstage app, backend) when release plugins

workspaces/bulk-import/plugins/bulk-import-backend/package.json, workspaces/bulk-import/plugins/bulk-import/package.json, workspaces/bulk-import/yarn.lock
Use workspace dependencies to fix #43
=> fix(bulk-import): use workspace dependencies to fix build

workspaces/bulk-import/plugins/bulk-import/src/components/Repositories/DeleteRepository.tsx, workspaces/bulk-import/plugins/bulk-import/src/types/response-types.ts, workspaces/bulk-import/plugins/bulk-import/src/types/types.ts, workspaces/bulk-import/plugins/bulk-import/src/utils/repository-utils.tsx
For [RHIDP-4144](https://issues.redhat.com/browse/RHIDP-4144)
Depends on #52 
Screen recording:
https://github.com/user-attachments/assets/e71f0eaf-1d6e-4bdd-aedf-7e9985fe2d38
=> fix(bulk-import): disable deletion button for non-location sourced repos

.github/workflows/automate_changeset_feedback.yml
This PR copies over the [automate-changeset-feedback.yml](https://github.com/backstage/community-plugins/blob/main/.github/workflows/automate_changeset_feedback.yml) workflow from backstage/community-plugins.
=> add a workflow to generate changeset feedback on PRs

workspaces/orchestrator/.changeset/red-boats-float.md, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts
FLPATH-1893
https://issues.redhat.com/browse/FLPATH-1893
=> fix(orchestrator): fix fetchWorkflowOverviewBySource to fetch less instances

.github/workflows/automate_changeset_feedback.yml
Adding this should hopefully edit the changeset feedback comment if it already exists instead of creating a new comment everytime. (based on what is mentioned here: https://github.com/backstage/actions/blob/main/changeset-feedback/action.yaml#L19)
=> add bot-username to changeset feedback workflow

workspaces/orchestrator/package.json, workspaces/orchestrator/packages/app/public/index.html, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DevModeService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/api/v2.test.ts, workspaces/orchestrator/plugins/orchestrator-form-react/src/utils/generateUiSchema.ts, workspaces/orchestrator/plugins/orchestrator/src/api/OrchestratorClient.test.ts, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx, workspaces/orchestrator/plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts, workspaces/orchestrator/yarn.lock
=> chore: unify prettier version

workspaces/lightspeed/.changeset/smart-books-rhyme.md, workspaces/lightspeed/plugins/lightspeed/src/hooks/__tests__/useConversationMessages.test.tsx, workspaces/lightspeed/plugins/lightspeed/src/hooks/useConversationMessages.ts
https://issues.redhat.com/browse/RHDHPAI-53
https://github.com/user-attachments/assets/7ded48e5-40a9-4ed5-a39e-14651ecde20d
cc: @jrichter1
=> fix(lightspeed): fix crash when switching between conversation during streaming

workspaces/orchestrator/.changeset/wicked-spoons-bow.md, workspaces/orchestrator/plugins/orchestrator-form-react/src/components/ReviewStep.tsx
=> fix(orchestrator): improve alignment of key-value pairs on the Review step

workspaces/bulk-import/.changeset/neat-news-rest.md, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx, workspaces/bulk-import/plugins/bulk-import/src/utils/repository-utils.tsx
Fix for [RHIDP-4954)](https://issues.redhat.com/browse/RHIDP-4954)
https://github.com/user-attachments/assets/183e1fb4-5d1f-4f97-b1db-295cbfdb6a43
=> fix(bulk-import): fixed `Check All` checkbox selection

workspaces/lightspeed/.changeset/modern-houses-hope.md, workspaces/lightspeed/plugins/lightspeed/README.md
This PR renames some  janus references in `README.md`.
=> plugin(lightspeed): rename janus references in README.md

workspaces/theme/.changeset/thirty-gorillas-live.md, workspaces/theme/plugins/theme/package.json, workspaces/theme/plugins/theme/src/componentOverrides.ts, workspaces/theme/plugins/theme/src/defaultThemePalette.ts, workspaces/theme/yarn.lock
I extracted the initial RHDH theme from https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src/themes/rhdh-1.2.0
=> feat(theme): migrate and release rhdh-theme 0.2.0 (RHDH 1.2)

workspaces/theme/.changeset/ninety-bees-raise.md, workspaces/theme/plugins/theme/CHANGELOG.md, workspaces/theme/plugins/theme/package.json, workspaces/theme/plugins/theme/report.api.md, workspaces/theme/plugins/theme/src/darkTheme.test.ts, workspaces/theme/plugins/theme/src/darkTheme.ts, workspaces/theme/plugins/theme/src/lightTheme.test.ts, workspaces/theme/plugins/theme/src/lightTheme.ts, workspaces/theme/plugins/theme/src/types.ts, workspaces/theme/plugins/theme/src/utils/createComponents.ts
Apply the latest changes from https://github.com/redhat-developer/red-hat-developer-hub-theme aka @redhat-developer/red-hat-developer-hub-theme@0.4.0.
This will release also a 0.4.0 version. :)
https://github.com/user-attachments/assets/b93c33c5-ac12-4b58-a9a8-23753564e686
It shows some theming issues we also have in our main branch, which we didn't had earlier afaik.
These issues are likely related to a Backstage or MUI update?
This PR restores what we had before and I will look into the theming issues after this is merged.
=> feat(theme): apply/migrate latest theme changes and release 0.4.0

workspaces/theme/.changeset/fresh-donuts-decide.md, workspaces/theme/plugins/theme/src/utils/createComponents.ts
For [RHIDP-5158](https://issues.redhat.com/browse/RHIDP-5158).
https://github.com/user-attachments/assets/feea8ff6-75b0-4ddf-829a-3380ff32b8a8
=> fix(theme): fixed Mui v5 outline button style

workspaces/bulk-import/.changeset/slow-trains-pretend.md, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
Small UI change, from:
to:
Change in the bottom right corner ;)
=> fix(bulk-import): fix add repository pagination padding/position

workspaces/theme/.changeset/strong-mangos-live.md, workspaces/theme/plugins/theme/package.json
=> fix(theme): fix sideEffect typo to load Red Hat font

workspaces/theme/.changeset/unlucky-singers-listen.md, workspaces/theme/plugins/theme/package.json
=> fix(theme): add style-inject(ion) workaround with the published package

workspaces/orchestrator/.changeset/modern-feet-wonder.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
resolves [FLPATH-1889](https://issues.redhat.com/browse/FLPATH-1889)
=> fix(orchestrator): rename column in workflow runs table

workspaces/bulk-import/yarn.lock, workspaces/homepage/yarn.lock, workspaces/lightspeed/yarn.lock, workspaces/marketplace/yarn.lock, workspaces/openshift-image-registry/yarn.lock, workspaces/orchestrator/yarn.lock, workspaces/theme/yarn.lock
This PR is to fix [CVE-2024-53983](https://nvd.nist.gov/vuln/detail/CVE-2024-53983)
=> chore: fix CVE-2024-53983

workspaces/orchestrator/.changeset/violet-teachers-fail.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTable.tsx
resolve [FLPATH-1887](https://issues.redhat.com/browse/FLPATH-1887)
=> fix(orchestrator): rename action tooltip in WorkflowsTable

workspaces/bulk-import/.changeset/twelve-pigs-agree.md, workspaces/bulk-import/plugins/bulk-import/dev/index.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebar.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/Repositories/AddedRepositoryTableRow.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/WaitingForPR.tsx, workspaces/bulk-import/plugins/bulk-import/src/hooks/useRepositories.ts, workspaces/bulk-import/plugins/bulk-import/src/types/types.ts, workspaces/bulk-import/plugins/bulk-import/src/utils/repository-utils.tsx, workspaces/bulk-import/plugins/bulk-import/tests/bulkImport.spec.ts
**Resolves:**
- https://issues.redhat.com/browse/RHIDP-4955
- https://issues.redhat.com/browse/RHIDP-5145
**GIF/Screenshot:**
https://github.com/user-attachments/assets/5f111c30-825d-40f8-b741-9edaaac7a3b8
=> fix[bulk-import]: persist changes made to the preview panel for jobs that are waiting for approval

workspaces/orchestrator/package.json, workspaces/orchestrator/packages/app/package.json, workspaces/orchestrator/plugins/orchestrator-backend/package.json, workspaces/orchestrator/plugins/orchestrator-common/package.json, workspaces/orchestrator/plugins/orchestrator-form-api/package.json, workspaces/orchestrator/plugins/orchestrator-form-react/package.json, workspaces/orchestrator/plugins/orchestrator-swf-editor-envelope/package.json, workspaces/orchestrator/plugins/orchestrator/package.json, workspaces/orchestrator/yarn.lock
=> chore(orchestrator): update dependencies

workspaces/orchestrator/.changeset/silent-taxis-burn.md, workspaces/orchestrator/plugins/orchestrator-form-react/package.json, workspaces/orchestrator/plugins/orchestrator-form-react/src/components/ReviewStep.tsx
resolve [FLPATH-1884](https://issues.redhat.com/browse/FLPATH-1884)
=> fix margin in back button

workspaces/orchestrator/.changeset/twelve-teachers-leave.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
resolve [FLPATH-1890](https://issues.redhat.com/browse/FLPATH-1890)
=> fix(orchestrator): hide abort button

workspaces/orchestrator/.changeset/big-needles-grin.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsCard.tsx
resolve [FLPATH-1968](https://issues.redhat.com/browse/FLPATH-1968)
=> fix(orchestrator):improve workflow details card in workflow page

workspaces/orchestrator/.changeset/chilly-hounds-brush.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
resolve [FLPATH-1966](https://issues.redhat.com/browse/FLPATH-1966)
Without assessedBy field
With assessedBy field
=> Update instance page

workspaces/orchestrator/.changeset/lucky-melons-play.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
resolve [FLPATH-1978](https://issues.redhat.com/browse/FLPATH-1978)
=> fix(orchestrator): Workflow progress panel should have a scroll

workspaces/orchestrator/.changeset/tiny-apples-yawn.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInputs.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
resolve [FLPATH-1976](https://issues.redhat.com/browse/FLPATH-1976)
=> fix(orchestrator): Implement inputs card in workflow instance page

workspaces/orchestrator/.changeset/cool-actors-greet.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
resolve [FLPATH-1986](https://issues.redhat.com/browse/FLPATH-1986)
=> fix(orchestrator):improve details in workflow instance page details card

CONTRIBUTING.md
This PR adds instructions to `CONTRIBUTING.md` on how to use the [Version Bump Workflow](https://github.com/redhat-developer/rhdh-plugins/actions/workflows/version-bump.yml) to update plugins to the latest version of Backstage.
=> add instuctions on how to use the version bump workflow

workspaces/global-floating-action-button/.changeset/eleven-fireants-cheat.md, workspaces/global-floating-action-button/plugins/global-floating-action-button/README.md
**Resolves:**
https://issues.redhat.com/browse/RHIDP-5419
**Review:**
https://github.com/debsmita1/rhdh-plugins/tree/fix-readme/workspaces/global-floating-action-button/plugins/global-floating-action-button
=> fix(fab): update global floating action button plugin readme

CONTRIBUTING.md
This PR adds explicit instructions on how to use the Version Bump Workflow and also includes who to ask for write access to the repository.
=> Update Version Bump Workflow instructions

workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts
fix typo following https://github.com/redhat-developer/rhdh-plugins/pull/247
=> fix(orchestrator): fix typo

workspaces/marketplace/.changeset/ten-chairs-think.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/README.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/package.json, workspaces/marketplace/plugins/marketplace-common/package.json, workspaces/marketplace/yarn.lock
align dependancies with backstage 1.32.0 in Marketplace plugin
=> chore(deps): align dependancies with backstage 1.32.0 in Marketplace plugin

workspaces/global-header/plugins/global-header/app-config.dynamic.yaml, workspaces/global-header/plugins/global-header/package.json, workspaces/global-header/plugins/global-header/src/index.ts, workspaces/global-header/plugins/global-header/src/plugin.ts, workspaces/global-header/yarn.lock
This PR works along with RHDH PR: [#2168](https://github.com/redhat-developer/rhdh/pull/2168)
=> fix(global-header): added some changes for integration with rhdh

workspaces/global-header/.changeset/quick-months-rush.md, workspaces/global-header/plugins/global-header/package.json
Publish the first version of global header plugin.
=> chore(global-header): publish first version of global header plugin

catalog-info-plugins-packages.yaml, catalog-info-plugins.yaml
=> chore: fix plugins and plugin-packages had the same name

workspaces/orchestrator/.changeset/selfish-knives-do.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
resolve [FLPATH-1975](https://issues.redhat.com/browse/FLPATH-1975)
running:
success:
failure:
=> fix(orchestrator):improve results card in workflow instance page

workspaces/orchestrator/.changeset/brown-rules-shop.md, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/OrchestratorService.test.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/OrchestratorService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/api/v2.test.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/api/v2.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/router.ts
FLPATH-1676
https://issues.redhat.com/browse/FLPATH-1676
=> replace abort mutation with call to delete in workflow pod

workspaces/orchestrator/docs/Permissions.md
=> chore(orchestrator): update doc for recent limitations

workspaces/orchestrator/README.md
Replace org-name `parodos-dev` with `rhdhorchestrator`
=> chore(orchestrator): Update org-name in README.md

workspaces/orchestrator/README.md
=> Update README.md (#339 backport)

workspaces/bulk-import/.changeset/curly-geckos-fold.md, workspaces/bulk-import/plugins/bulk-import/README.md
updates readme to point to right link
=> docs(bulk-import): updates readme to point to right link

workspaces/global-floating-action-button/.changeset/brave-hornets-compare.md, workspaces/global-floating-action-button/plugins/application-listener-test/README.md, workspaces/global-floating-action-button/plugins/application-listener-test/app-config.dynamic.yaml, workspaces/global-floating-action-button/plugins/application-listener-test/report.api.md, workspaces/global-floating-action-button/plugins/application-listener-test/src/components/CrashListener.ts, workspaces/global-floating-action-button/plugins/application-listener-test/src/plugin.ts
Adds a new `CrashListener` and updates the README
The link in the README depends on https://github.com/redhat-developer/rhdh/pull/2199 and should work soon. :)
=> feat(application-listener-test): add CrashListener and update readme

workspaces/orchestrator/.changeset/thirty-toys-relax.md, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts
FLPATH-2009
https://issues.redhat.com/browse/FLPATH-2009
=> improve data index network errors

workspaces/global-header/plugins/global-header/src/components/GlobalHeader.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/CreateDropdown.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/HeaderDropdownComponent.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/MenuSection.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/RegisterAComponentSection.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderLinkComponent/HeaderItemContent.tsx
For [RHIDP-5364](https://issues.redhat.com/browse/RHIDP-5364)
Screen recording(updated on Feb 4th)
Testing with [RHDH PR #2263](https://github.com/redhat-developer/rhdh/pull/2263)
https://github.com/user-attachments/assets/95da30d9-86f4-4ec9-bbc3-32d93e047f12
=> fix(global-header): enable theme matching

workspaces/lightspeed/packages/app/e2e-tests/app.test.ts, workspaces/lightspeed/packages/app/e2e-tests/fixtures/responses.ts, workspaces/lightspeed/packages/app/e2e-tests/lightspeed.test.ts, workspaces/lightspeed/packages/app/e2e-tests/utils/testHelper.ts, workspaces/lightspeed/playwright.config.ts
Adds more lightspeed specific playwright tests for dev mode
Install playwright dependencies if need be `npx playwright install`
Run with `npx playwright test`
=> test(lightspeed): Add more dev mode automation

workspaces/marketplace/.changeset/sour-hornets-shake.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/report.api.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePluginProcessor.test.ts, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/MarketplacePluginProcessor.ts
Shows the relationships between plugin and packages.
=> feat(marketplace): add plugin entity relationship with package entity

workspaces/marketplace/.changeset/green-eyes-run.md, workspaces/marketplace/plugins/marketplace-common/report.api.md, workspaces/marketplace/plugins/marketplace-common/src/types.ts
Add types for documentation, assets and deprecate old installation status and description.
=> fix(marketplace): add documentation and asset types

workspaces/global-floating-action-button/.changeset/two-ants-jam.md, workspaces/global-floating-action-button/plugins/global-floating-action-button/README.md, workspaces/global-floating-action-button/plugins/global-floating-action-button/dev/index.tsx, workspaces/global-floating-action-button/plugins/global-floating-action-button/src/hooks/useFabMountPoints.ts
Resolves: https://issues.redhat.com/browse/RHIDP-5844
=> feat(fab): update mount point name

workspaces/orchestrator/.changeset/yellow-humans-share.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPageTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowsTable.tsx
resolve [FLPATH-772](https://issues.redhat.com/browse/FLPATH-772)
I made loading times deliberately longer for this video , unless it's too fast to see:
https://github.com/user-attachments/assets/85e1d132-c8f2-4918-bdb0-c112fd9b70db
=> fix(orchestrator):Standardise the page loading animation

workspaces/theme/.changeset/modern-deers-itch.md, workspaces/theme/plugins/theme/src/hooks/useThemeConfig.ts
Fixed [RHIDP-5902](https://issues.redhat.com/browse/RHIDP-5902)
=> fix(theme): Fixing fontColor error while customizing rhdh appearance

workspaces/orchestrator/.changeset/breezy-queens-matter.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
resolve [FLPATH-2065](https://issues.redhat.com/browse/FLPATH-2065)
=> [rc9] MTA displays two statuses in results when failing with error

workspaces/global-header/app-config.yaml, workspaces/global-header/catalog-info.yaml, workspaces/global-header/docs/index.md, workspaces/global-header/mkdocs.yaml, workspaces/global-header/plugins/global-header/dev/configuration.md
Some initial tech docs. Not complete of course.
=> docs(global-header): add initial tech docs

workspaces/orchestrator/.changeset/tough-queens-hope.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
resolve [FLPATH-2068](https://issues.redhat.com/browse/FLPATH-2068)
=> fix(orchestrator): [UI] Empty values section in Results pane should not be rendered

workspaces/orchestrator/.changeset/small-mugs-watch.md, workspaces/orchestrator/app-config.yaml, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DevModeService.ts
- Added check for resourcesPath before cloning 
- Added code to remove the git history of the cloned workflow repo to prevent any future issues with git submodules
- Reverted app-config.yaml change made by https://github.com/redhat-developer/rhdh-plugins/commit/4b008c4b9f547d101e6d71f29a31627c86401d99
Created based on discussion here: https://redhat.enterprise.slack.com/archives/C059YMMB664/p1739370779251939
=> fix(orchestrator): improved devMode, revert last yaml change

.github/CODEOWNERS
This is a request to add coreydaley as a codeowner to manage the security requirements of this repo
=> chore: add coreydaley as a codeowner

workspaces/orchestrator/.changeset/popular-months-watch.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsCard.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPageTabContent.tsx
resolve [FLPATH-2066](https://issues.redhat.com/browse/FLPATH-2066)
=> fix(orchestrator):[UI] Layout errors with workflow details screen

workspaces/orchestrator/entities/convertWorkflowToTemplate.yaml
Updating documentation of the `convertWorkflowToTemplate`
=> chore(orchestrator): update GitLab comments of convertWorkflowToTemplate

workspaces/global-header/.changeset/seven-queens-whisper.md, workspaces/global-header/plugins/global-header/dev/index.tsx, workspaces/global-header/plugins/global-header/package.json, workspaces/global-header/plugins/global-header/report.api.md, workspaces/global-header/plugins/global-header/src/components/NotificationBanner.tsx, workspaces/global-header/yarn.lock
Tiny changes to NotificationBanner and esp. incl. a changeset to release global-header plugin 1.0.0 :partying_face:
=> feat(global-header): release global-header 1.0.0

workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInputs.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
=> fix(orchestrator):fix cards order on workflow instance page

workspaces/orchestrator/.changeset/many-cats-drum.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
=> fix(orchestrator): workaround for Completed state with an error message

workspaces/orchestrator/.changeset/many-cats-drum.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
=> fix(orchestrator): workaround for Completed state with an error message (backport)

workspaces/orchestrator/.changeset/friendly-fireants-attend.md, workspaces/orchestrator/docs/rbac-policy.csv, workspaces/orchestrator/plugins/orchestrator-common/report.api.md, workspaces/orchestrator/plugins/orchestrator-common/src/permissions.ts, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsTabContent.tsx
resolve [FLPATH-1916](https://issues.redhat.com/browse/FLPATH-1916)
=> fix(orchestrator):Limit viewable component to specific roles

workspaces/marketplace/.changeset/heavy-melons-matter.md, workspaces/marketplace/app-config.dynamic.yaml, workspaces/marketplace/plugins/catalog-backend-module-marketplace/package.json, workspaces/marketplace/plugins/marketplace-common/package.json, workspaces/marketplace/plugins/marketplace-common/report.api.md, workspaces/marketplace/plugins/marketplace-common/src/api/MarketplaceBackendClient.ts, workspaces/marketplace/plugins/marketplace-common/src/api/MarketplaceCatalogClient.ts, workspaces/marketplace/plugins/marketplace-common/src/types/MarketplaceCollection.ts, workspaces/marketplace/plugins/marketplace-common/src/types/MarketplacePackage.ts, workspaces/marketplace/plugins/marketplace-common/src/types/MarketplacePlugin.ts, workspaces/marketplace/plugins/marketplace/src/components/CollectionHorizontalScrollRow.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogGrid.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCollectionGrid.tsx, workspaces/marketplace/yarn.lock
Remove some dependencies and address tiny issues
=> fix(marketplace): fix dynamic plugin build issues

workspaces/marketplace/.changeset/twelve-apes-fix.md, workspaces/marketplace/plugins/marketplace/app-config.dynamic.yaml
fix(marketplace): fix mount points in app-config.dynamic.yaml
=> fix(marketplace): fix mount points in app-config.dynamic.yaml

workspaces/marketplace/.changeset/serious-moose-notice.md, workspaces/marketplace/plugins/marketplace/src/pages/DynamicMarketplacePluginRouter.tsx
=> fix(marketplace): rename to extensions/catalog

workspaces/marketplace/.changeset/witty-sloths-matter.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePackageDrawer.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginDrawer.tsx
Fix issue with drawer content for items with less content.
See Backstage Search plugin
=> fix(marketplace): fix drawer background color

workspaces/orchestrator/.changeset/breezy-shrimps-tell.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
=> fix compilation

workspaces/marketplace/.changeset/early-weeks-double.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginFilter.tsx, workspaces/marketplace/plugins/marketplace/src/shared-components/BackstageSelectFilter.tsx
Removes the filters text, horizontal divider and extra padding on top.
Screenshots:
=> fix(marketplace): remove Filters text and divider

workspaces/marketplace/.changeset/small-timers-shout.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/providers/BaseEntityProvider.ts
https://issues.redhat.com/browse/RHIDP-6365
=> fix(marketplace): Fix certified badge annotation in marketplace provider.

workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
Postgres database automatically transforms the came case column names to lowercase, so this PR explicitly make the column name lowercase so that both sqlite and postgres results in same format."
=> fix(adoption-insights): camel case column names to lower case

workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/adapters/BaseAdapter.ts
Fixes:
https://issues.redhat.com/browse/RHDHPAI-672
This PR explicitly casts the counts in the response to INTEGER, so there is no discrepancies between databases and add more metadata for techdocs api.
Before:
After:
---
add more metadata i.e `name`, `namespace` and `kind` for Techdocs API.
=> fix(adoption-insights): add more metadata and cast count as integers

workspaces/marketplace/examples/plugins/tekton.yaml, workspaces/marketplace/plugins/marketplace/package.json, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx, workspaces/marketplace/yarn.lock
This is for [RHIDP-6277](https://issues.redhat.com/browse/RHIDP-6277)
=> feat(marketplace): add install page

workspaces/marketplace/plugins/marketplace/src/utils.test.ts, workspaces/marketplace/plugins/marketplace/src/utils.ts
=> feat(marketplace): add tests for the utils

workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx, workspaces/marketplace/plugins/marketplace/src/utils.test.ts, workspaces/marketplace/plugins/marketplace/src/utils.ts
fix applied example being treated as a string rather an object
Before:
After:
=> fix applied example being treated as a string rather an object

workspaces/global-header/.changeset/tasty-years-listen.md, workspaces/global-header/plugins/global-header/src/components/LogoutButton/LogoutButton.tsx
Resolving [RHIDP-6334](https://issues.redhat.com/browse/RHIDP-6334)
**Description :**  The logout button should be renamed to Sign Out
RHDH UI Screenshot
=> feat(global-header): changing Logout to Sign out

workspaces/global-header/.changeset/famous-birds-sniff.md, workspaces/global-header/plugins/global-header/dev/index.tsx, workspaces/global-header/plugins/global-header/report.api.md, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ApplicationLauncherDropdown.test.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ApplicationLauncherDropdown.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/DropdownEmptyState.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/StarredDropdown.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderIcon/HeaderIcon.tsx, workspaces/global-header/plugins/global-header/src/components/MenuItemLink/MenuItemLink.tsx, workspaces/global-header/plugins/global-header/src/components/MenuItemLink/MenuItemLinkContent.tsx, workspaces/global-header/plugins/global-header/src/components/SupportButton/SupportButton.tsx, workspaces/global-header/plugins/global-header/src/defaultMountPoints/defaultMountPoints.tsx, workspaces/global-header/plugins/global-header/src/hooks/useApplicationLauncherDropdownMountPoints.ts, workspaces/global-header/plugins/global-header/src/plugin.ts, workspaces/global-header/plugins/global-header/src/types.ts
Fixes: https://issues.redhat.com/browse/RHDHPAI-664
This PR adds the ability to configure application launcher links in global header.
https://github.com/user-attachments/assets/f2e41876-e67a-43dc-84c0-af93ae8f1284
=> feat(global-header): add new app launcher dropdown

workspaces/marketplace/.changeset/seven-laws-grin.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePackageInstallContent.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx
Button section in dark mode Before
Button section in dark mode After
Install page cards height Before
Install page cards height After
=> fix(marketplace): minor UI updates

workspaces/orchestrator/.changeset/sour-colts-unite.md, workspaces/orchestrator/docs/LoginAsAdmin.md
resolve [FLPATH-2137](https://issues.redhat.com/browse/FLPATH-2137)
=> Add LoginAsAdmin readme file

workspaces/bulk-import/.changeset/brown-ways-build.md, workspaces/bulk-import/plugins/bulk-import-backend/README.md, workspaces/bulk-import/plugins/bulk-import-backend/package.json, workspaces/bulk-import/plugins/bulk-import-backend/report.api.md, workspaces/bulk-import/plugins/bulk-import-backend/src/helpers/auditLogUtils.ts, workspaces/bulk-import/plugins/bulk-import-backend/src/helpers/auditorUtils.ts, workspaces/bulk-import/plugins/bulk-import-backend/src/helpers/auth.ts, workspaces/bulk-import/plugins/bulk-import-backend/src/plugin.ts, workspaces/bulk-import/plugins/bulk-import-backend/src/service/router.ts, workspaces/bulk-import/yarn.lock
Use newer audit-log package from Backstage.
Fixes: https://issues.redhat.com/browse/RHIDP-5988
=> fix(bulk-import): use newer audit-log package from Backstage

workspaces/marketplace/.changeset/pretty-news-suffer.md, workspaces/marketplace/packages/cli/src/commands/export-csv/index.ts
Fixes: https://issues.redhat.com/browse/RHIDP-6697
Minor `export-csv` fixes, and add more columns per request
=> fix(marketplace): minor export-csv fixes

workspaces/orchestrator/.changeset/brave-mayflies-melt.md, workspaces/orchestrator/plugins/orchestrator/src/components/InfoDialog.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
resolve [FLPATH-2202](https://issues.redhat.com/browse/FLPATH-2202)
=> fix(orchestrator): fix view variables screen

workspaces/ai-integrations/plugins/ai-experience/src/components/AiExperienceHomePage/AiExperienceHomePage.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/LearnSection/CardWrapper.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/LearnSection/LearnSection.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/CardWrapper.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/ModelSection.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/ModelSection/TagList.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/SectionWrapper/SectionWrapper.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/TemplateSection/CardWrapper.tsx
This PR introduces the following changes:
- Improved responsiveness and layout
- if display name not available make `Guest` default
- added tags component
=> fix(ai-integrations): improve responsiveness and layout

workspaces/orchestrator/.changeset/gorgeous-kiwis-sleep.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx
resolve [https://issues.redhat.com/browse/FLPATH-2234](FLPATH-2234)
=> fix(orchestrator): run button should match figma

workspaces/adoption-insights/.changeset/thick-knives-eat.md, workspaces/adoption-insights/plugins/adoption-insights/src/api/__tests__/index.test.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/api/index.ts, workspaces/adoption-insights/plugins/adoption-insights/src/components/ActiveUsers/ActiveUsers.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/CatalogEntities/CatalogEntities.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/CatalogEntities/__tests__/CatalogEntities.test.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Plugins/Plugins.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Searches/Searches.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Techdocs/Techdocs.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Techdocs/__tests__/Techdocs.test.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Templates/Templates.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Templates/__tests__/Templates.test.tsx, workspaces/adoption-insights/plugins/adoption-insights/src/components/Users/Users.tsx
[#607](https://github.com/redhat-developer/rhdh-plugins/issues/607)
- Improved error management for API failures
=> fix(adoption-insights): add error management for API failures

workspaces/theme/.changeset/quick-jobs-play.md, workspaces/theme/.changeset/version-bump-1-36-1.md
For [RHIDP-6601](https://issues.redhat.com/browse/RHIDP-6601), [RHIDP-6603](https://issues.redhat.com/browse/RHIDP-6603). This PR fixed a mixed changeset issue on release theme CI.
=> fix(theme): updated changeset

workspaces/theme/plugins/theme/CHANGELOG.md, workspaces/theme/plugins/theme/package.json
=> chore(theme): Package version for theme

workspaces/orchestrator/.changeset/dull-worms-agree.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowResult.tsx
=> fix(orchestrator): fix bug in workflow result

workspaces/ai-integrations/.changeset/funny-numbers-pull.md, workspaces/ai-integrations/app-config.yaml
simplify config for both local dev and rhdh pod
- [/ ] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
=> for time being we can use localhost in both dev and rhdh pod scenarios

workspaces/orchestrator/.changeset/cuddly-weeks-protect.md, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/InputSchemaDialog.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/OrchestratorPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowRunsTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowsTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowsTable.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/Router.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx
resolve [FLPATH-2248](https://issues.redhat.com/browse/FLPATH-2248)
Orchestrator page folder was created as well
=> fix(orchestrator):Add option to view input schema from workflows table

workspaces/bulk-import/.changeset/honest-garlics-greet.md, workspaces/bulk-import/plugins/bulk-import/package.json, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositories.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/Illustrations.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/RepositoriesSearchBar.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/BulkImportPage.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/Repositories/RepositoriesAddLink.tsx, workspaces/bulk-import/plugins/bulk-import/src/components/WaitingForPR.tsx, workspaces/bulk-import/plugins/bulk-import/src/index.ts, workspaces/bulk-import/yarn.lock, workspaces/global-floating-action-button/plugins/global-floating-action-button/src/components/FloatingButton.tsx
**Resolves:**
- https://issues.redhat.com/browse/RHIDP-6455
**GIF from rhdh local:**
https://github.com/user-attachments/assets/1d9d51e3-02de-4bec-91c4-1c5c49cd3566
**How to test:**
Run from `rhdh-plugins/workspaces/bulk-import/plugins/bulk-import`
```yarn build```
```
sudo npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root /<path-to-your-rhdh>/rhdh/dynamic-plugins-root --dev
```
Run from `rhdh-plugins/workspaces/global-floating-action-button/plugins/global-floating-action-button`
```yarn build```
```
sudo npx --yes @janus-idp/cli package export-dynamic-plugin --dynamic-plugins-root /<path-to-your-rhdh>/rhdh/dynamic-plugins-root --dev
```
Run from `rhdh`
```
yarn dev
```
=> fix(bulk-import): add MUI class generator

workspaces/global-floating-action-button/.changeset/two-mayflies-dream.md
Added the missing changeset as part of https://github.com/redhat-developer/rhdh-plugins/pull/592 to release a patch version
=> chore(fab): add the missing changeset

workspaces/bulk-import/.changeset/moody-chicken-design.md, workspaces/bulk-import/plugins/bulk-import/src/components/PreviewFile/PreviewPullRequestForm.tsx
Reverts redhat-developer/rhdh-plugins#625
=> Revert "fix(bulk-import): fix runtime error on click of Preview PR"

workspaces/ai-integrations/plugins/ai-experience/README.md
This PR updates the AI experience plugin Readme documentation.
=> docs(ai-experience): update ai-experience plugin README file

workspaces/marketplace/.changeset/nervous-nails-travel.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginFilter.tsx, workspaces/marketplace/plugins/marketplace/src/hooks/useQueryArrayFilter.ts, workspaces/marketplace/plugins/marketplace/src/shared-components/CustomSelectFilter.tsx
Resolves
https://issues.redhat.com/browse/RHIDP-7014
=> fix(extensions): fix issue with deselecting the selected filter

workspaces/orchestrator/.changeset/spicy-parents-run.md, workspaces/orchestrator/docs/rbac-policy.csv, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/router.ts
resolve [FLPATH-2259](https://issues.redhat.com/browse/FLPATH-2259)
=> fix(orchestrator):Fix instance fetching to respect permissions

workspaces/orchestrator/.changeset/clean-rules-develop.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx
resolve [FLPATH-2283](https://issues.redhat.com/browse/FLPATH-2283)
=> fix(orchestrator):change breadcrumbs titles

workspaces/sandbox/.changeset/moody-toes-learn.md, workspaces/sandbox/README.md, workspaces/sandbox/app-config.yaml, workspaces/sandbox/packages/app/src/App.tsx, workspaces/sandbox/plugins/sandbox/app-config.dynamic.yaml, workspaces/sandbox/plugins/sandbox/config.d.ts, workspaces/sandbox/plugins/sandbox/dev/index.tsx, workspaces/sandbox/plugins/sandbox/src/api/AnsibleBackendClient.tsx, workspaces/sandbox/plugins/sandbox/src/api/KubeBackendClient.tsx, workspaces/sandbox/plugins/sandbox/src/api/RegistrationBackendClient.tsx, workspaces/sandbox/plugins/sandbox/src/api/SecureFetchClient.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/AnsibleLaunchInfoModal.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/PhoneNumberStep.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/VerificationCodeStep.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogBanner.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogCard.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/SandboxCatalogCardButton.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/__tests__/productData.test.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/productData.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxHeader.tsx, workspaces/sandbox/plugins/sandbox/src/hooks/useSandboxContext.tsx, workspaces/sandbox/plugins/sandbox/src/plugin.test.ts, workspaces/sandbox/plugins/sandbox/src/plugin.ts
Jira: https://issues.redhat.com/browse/RHDHPAI-769
This pull request introduces significant updates to the Developer Sandbox, including changes to routing, configuration, API clients, and UI components. The most important changes involve simplifying routing paths, replacing `DiscoveryApi` with `ConfigApi` for backend clients, and enhancing the user interface for better usability and consistency.
* Updated the default route from `/home` to `/` across multiple files, including `README.md`, `App.tsx`, and `dev/index.tsx`, to simplify navigation and align with standard practices. [[1]](diffhunk://#diff-5b50c8ca2f8e4cdafa50656b04a8f8126752f232965d978dcf92b656c989c669L27-R27) [[2]](diffhunk://#diff-bf6790fb8bb1e2157eb1509f0d8d17e8976741a8501e35f2a1dac6983e395815L85) …
=> RHDHPAI-769: Sandbox Plugin Bug fixes

workspaces/ai-integrations/plugins/ai-experience/app-config.dynamic.yaml, workspaces/ai-integrations/plugins/ai-experience/report.api.md, workspaces/ai-integrations/plugins/ai-experience/src/plugin.ts
=> feat(ai-news): export AI news icon

workspaces/ai-integrations/plugins/ai-experience/src/components/NewsPage/NewsCard.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/NewsPage/NewsHeader.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/__tests__/NewsCard.test.tsx
- Fixed the issues poined out in https://github.com/thepetk/rhdh-gitops/pull/2#issuecomment-2839257661
- FIxed the CSS Image issue observed in Rolling Demo cluster
- Fixed the page title issue
=> Fix(AI-Experience): CSS Fixes

.github/CODEOWNERS
=> Add Sandbox team to Sanbox workspace CODEOWNERS

workspaces/ai-integrations/plugins/ai-experience/src/components/LearnSection/CardWrapper.tsx, workspaces/ai-integrations/plugins/ai-experience/src/components/LearnSection/LearnSection.tsx, workspaces/ai-integrations/plugins/ai-experience/src/utils/constants.ts
This PR contains Onboarding Link change in AI Homepage plugin (Go to techdocs). As per Ben comments it got changed ([Link](https://www.figma.com/design/6ORS1mhUaxeyTBjMmE95Rn?node-id=2052-1169&m=dev#1234617191)).
=> fix(ai-integrations): update onboarding link

workspaces/orchestrator/.changeset/tame-cycles-crash.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/README.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-test-server/exampleWorkflows/schemas/dynamic_schema__main-schema.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-test-server/index.js, workspaces/orchestrator/plugins/orchestrator-form-widgets/package.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/FormWidgetsApi.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/applySelector.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/index.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/safeSet.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useGetExtraErrors.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useRequestInit.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useRetriggerEvaluate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveTextInput.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ErrorText.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx, workspaces/orchestrator/yarn.lock
Adds `ActiveTextInput` component with loading of defaults, validation and autocomplete.
Infra for asycn validation and selectors is added as well.
=> feat(orchestrator): ActiveTextInput widget

workspaces/orchestrator/plugins/orchestrator/src/api/OrchestratorClient.ts
This patch fixes the need to log into all so far supported SCM providers before executing any workflow.
Follow-up for #611 .
This part is further planed to be updated within FLPATH-2314.
In a nutshell, we plan to request selected SCM logins during the input parameters collection and then silently collect them at Run the way as #611 suggests.
Before:
=> fix(orchestrator): avoid forced SCM login at workflow run

workspaces/marketplace/.changeset/renovate-4e2b708.md, workspaces/marketplace/packages/app/package.json, workspaces/marketplace/yarn.lock
Fix invalid changeset from #396 and align the two package.jsons where the theme was loaded
=> fix(marketplace): finish theme update and fix changeset

workspaces/global-header/.changeset/old-dots-sparkle.md, workspaces/global-header/packages/app/package.json, workspaces/global-header/packages/app/src/App.tsx, workspaces/global-header/plugins/global-header/dev/index.tsx, workspaces/global-header/plugins/global-header/package.json, workspaces/global-header/plugins/global-header/src/components/GlobalHeaderComponent.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/CreateDropdown.tsx, workspaces/global-header/plugins/global-header/src/components/SearchComponent/SearchInput.tsx, workspaces/global-header/yarn.lock
=> feat(global-header): use new theme package

workspaces/orchestrator/plugins/orchestrator-form-widgets/README.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/README.md, workspaces/orchestrator/plugins/orchestrator/docs/orchestratorFormWidgets.md
Fixes: FLPATH-2291
Documentation for a workflow developer using the widgets library.
=> chore(orchestrator): user documentation for orchestrator-form-widgets

workspaces/bulk-import/.changeset/violet-planes-greet.md, workspaces/bulk-import/plugins/bulk-import/src/components/AddRepositories/AddRepositories.tsx
Resolves:
https://issues.redhat.com/browse/RHIDP-7478
Screenshot:
Before:
After:
=> fix(bulk-import): fix import api error message for generic error

workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/Dockerfile, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/package.json
=> chore(orchestrator): Dockerfile for http-workflow-dev-server

workspaces/orchestrator/plugins/orchestrator-form-widgets/package.json
=> fix(orchestrator): add scalprum section to package.json

workspaces/orchestrator/packages/app/src/App.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveTextInput.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/constants.ts
Debounce fetch in active widgets
=> chore(orchestrator): debounce fetch

workspaces/orchestrator/plugins/orchestrator-form-react/src/DefaultFormApi.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/report.api.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/FormWidgetsApi.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/index.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/plugin.ts
=> chore(orchestrator): log which OrchestratorFormApi is used

workspaces/orchestrator/plugins/orchestrator-form-widgets/package.json, workspaces/orchestrator/plugins/orchestrator/package.json
=> chore(orchestrator): rename exposed OrchestratorFormWidgetsPlugin to PluginRoot

workspaces/lightspeed/.changeset/sour-geckos-hope.md, workspaces/lightspeed/plugins/lightspeed/src/api/LightspeedApiClient.ts, workspaces/lightspeed/plugins/lightspeed/src/api/api.ts, workspaces/lightspeed/plugins/lightspeed/src/components/Attachment.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/AttachmentContext.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/FilePreview.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/LightspeedChatBox.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/LightspeedPage.tsx, workspaces/lightspeed/plugins/lightspeed/src/hooks/__tests__/useConversationMessages.test.tsx, workspaces/lightspeed/plugins/lightspeed/src/hooks/useConversationMessages.ts, workspaces/lightspeed/plugins/lightspeed/src/hooks/useCreateCoversationMessage.ts, workspaces/lightspeed/plugins/lightspeed/src/types.ts, workspaces/lightspeed/plugins/lightspeed/src/utils/__tests__/attachment-utils.test.ts, workspaces/lightspeed/plugins/lightspeed/src/utils/attachment-utils.ts, workspaces/lightspeed/plugins/lightspeed/src/utils/lightspeed-chatbox-utils.ts
https://issues.redhat.com/browse/RHDHPAI-555
https://issues.redhat.com/browse/RHDHPAI-758
https://issues.redhat.com/browse/RHDHPAI-762
This PR adds the following:
- Attachment support from UI. Supported file type - `.yaml`, `.json` and `.txt` files.
- Updated Functional and Legal Disclaimers
- Updated welcome prompts on new conversation page. (Hard coded for now, will make it configurable in followup PR)
- Shows Citation links if the responses contains the information.
Functional and Legal Disclaimers:
Attachement demo:
https://github.com/user-attachments/assets/edeb5f77-b6c9-49b0-b479-66de01024b7b
Attachment preview:
Edit attachment:
Attachment Error states:
---
---
=> feat(lightspeed): add attachment support and disclaimers

workspaces/marketplace/.changeset/shaggy-rules-fix.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/module.ts, workspaces/marketplace/plugins/marketplace-backend/package.json, workspaces/marketplace/plugins/marketplace-backend/src/permissions/rules.ts, workspaces/marketplace/plugins/marketplace-backend/src/plugin.ts, workspaces/marketplace/plugins/marketplace-backend/src/router.test.ts, workspaces/marketplace/plugins/marketplace-backend/src/router.ts, workspaces/marketplace/plugins/marketplace-common/package.json, workspaces/marketplace/plugins/marketplace-common/report.api.md, workspaces/marketplace/plugins/marketplace-common/src/api/MarketplaceApi.ts, workspaces/marketplace/plugins/marketplace-common/src/api/MarketplaceBackendClient.ts, workspaces/marketplace/plugins/marketplace-common/src/permissions.ts, workspaces/marketplace/plugins/marketplace/README.md, workspaces/marketplace/plugins/marketplace/package.json, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx, workspaces/marketplace/plugins/marketplace/src/consts.ts, workspaces/marketplace/plugins/marketplace/src/hooks/usePluginConfigurationPermissions.ts, workspaces/marketplace/plugins/marketplace/src/pages/MarketplaceHomePage.tsx, workspaces/marketplace/plugins/marketplace/src/pages/MarketplaceTabbedPageRouter.tsx, workspaces/marketplace/plugins/marketplace/src/plugin.test.ts, workspaces/marketplace/plugins/marketplace/src/plugin.ts, workspaces/marketplace/plugins/marketplace/src/routes.ts, workspaces/marketplace/yarn.lock
Addressed review comments from https://github.com/redhat-developer/rhdh-plugins/pull/691
Resolves: https://issues.redhat.com/browse/RHIDP-7547
Updated frontend plugin Readme
**How to test:**
Install rbac frontend and backend plugins
Add the Github signin page
Add the following in you rbac-policy.csv file
```
g, user:default/<github-id>, role:default/admins
p, role:default/admins, catalog-entity, read, allow
p, role:default/admins, catalog.entity.create, create, allow
p, role:default/admins, catalog.location.read , read, allow
p, role:default/admins, catalog.location.create , create, allow
p, role:default/admins, extensions-plugin, read, allow
p, role:default/admins, extensions-plugin, create, allow
```
Add the following to your `app-config.yaml`
```
permission:
enabled: true
rbac: …
```
=> feat(extensions): update marketplace pluginId to extensions

package.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/exampleWorkflows/schemas/dynamic-course-select__main-schema.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/exampleWorkflows/schemas/dynamic_schema__main-schema.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/httpServer.dynamic.course.select.js, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/index.js, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/FormWidgetsApi.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/uiPropTypes.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/errorUtils.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.test.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/index.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useFetch.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useFetchAndEvaluate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useRetriggerEvaluate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useTemplateUnitEvaluator.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveText.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/StaticText.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/index.ts, yarn.lock
[FLPATH-2288](https://issues.redhat.com/browse/FLPATH-2288) Implemented StaticText component for orchestrator widgets library.
Includes fix in retrigger in widgets library.
=> feat(orchestrator): added StaticText widget to form widgets library

.github/workflows/release_workspace_version.yml
* d4e18e76e09532b0d1abe829fdd3d029ee4adafe: Copies over the interim release workflow from Backstage Community Plugins, follow their documentation at https://github.com/backstage/community-plugins/blob/main/docs/plugin-maintainers-guide.md#maintaining-and-patching-an-older-release-line
* fac674649a6c98a5c0319da0c0c78124ae2351d8: updates to align with our environment variables and bot account name
=> feat(ci): add interim release workflow

workspaces/orchestrator/docs/orchestratorFormWidgets.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/exampleWorkflows/dynamic.course.select.sw.yaml, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/exampleWorkflows/schemas/dynamic-course-select__main-schema.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/httpServer.dynamic.course.select.js, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/FormWidgetsApi.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useFetch.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useGetExtraErrors.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useTemplateUnitEvaluator.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveDropdown.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveTextInput.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/index.ts
=> feat(orchestrator): ActiveDropdown and other updates

workspaces/orchestrator/.changeset/cuddly-plants-ring.md, workspaces/orchestrator/plugins/orchestrator-backend/src/service/OrchestratorService.test.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/OrchestratorService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/api/v2.ts, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowsTable.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/RunButton.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsCard.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowStatus.tsx
resolve [FLPATH-2301](https://issues.redhat.com/browse/FLPATH-2301)
**Available** 
**Unavailable**
=> fix(orchestrator): Add workflow status

workspaces/global-header/.changeset/grumpy-trainers-turn.md, workspaces/global-header/plugins/global-header/package.json, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ProfileDropdown.test.tsx, workspaces/global-header/plugins/global-header/src/components/HeaderDropdownComponent/ProfileDropdown.tsx, workspaces/global-header/yarn.lock
Part of https://issues.redhat.com/browse/RHIDP-7381
Original PR https://github.com/redhat-developer/rhdh-plugins/pull/792
=> fix(global-header): fix global-header to prioritize 'spec.profile.displayname'

workspaces/orchestrator/docs/extensibleForm.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/README.md
To be aligned with recent code.
=> chore(orchestrator): update documentation for Workflow Execution Form extensions

.github/renovate-presets/workspace/rhdh-orchestrator-presets.json
Fix syntax-  missing `/`
https://issues.redhat.com/browse/RHIDP-6050
=> chore: fix orchestrator preset

.github/renovate.json
Add Openshift Image Registry to main renovate config.  Labels were not being added to the PR 
https://issues.redhat.com/browse/RHIDP-6050
=> chore: add openshift-image-registry preset

workspaces/orchestrator/.changeset/quick-birds-provide.md, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.test.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-common/report.api.md, workspaces/orchestrator/plugins/orchestrator-common/src/models.ts
TO BE MERGED ONLY AFTER SONATA HAVE A RELEASE with changes for https://github.com/apache/incubator-kie-issues/issues/1857
FLPATH-2136
https://issues.redhat.com/browse/FLPATH-2136
=> fix(orchestrator): remove failed nodes from previous executions

workspaces/marketplace/.changeset/curvy-fireants-beam.md, workspaces/marketplace/plugins/marketplace/src/components/PluginCard.tsx
Highlight Category chips when keyboard focus is given
Fix : https://issues.redhat.com/browse/RHIDP-6544
https://github.com/user-attachments/assets/908870af-837e-4397-9a8e-3121c7d27869
=> fix(marketplace): highlight category chips when keyboard focus is given

workspaces/global-header/packages/app/package.json, workspaces/global-header/packages/app/src/App.tsx, workspaces/global-header/packages/app/src/components/Root/Root.tsx, workspaces/global-header/yarn.lock
For [RHIDP-7492](https://issues.redhat.com/browse/RHIDP-7492)
Main changes:
1. Set `above-sidebar` position as default header position in dev app
2. Fixed main content border radius when scrollbar shows up
3. Excluded main content header from scrollable part when content is long
4. Fixed double scrollbars issue when header is enabled
Before:
https://github.com/user-attachments/assets/f8571c8f-84ed-4aa1-96dc-2dc7bb1a4f9d
After:
https://github.com/user-attachments/assets/bb92bf61-0090-470a-ae08-84834284eed6
=> fix(global-header): set above-sidebar as default header position in dev

workspaces/orchestrator/plugins/orchestrator-form-widgets/http-workflow-dev-server/exampleWorkflows/schemas/dynamic-course-select__main-schema.json, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useGetExtraErrors.ts
Minor change, side-effect of debugging FLPATH-2359.
=> chore(orchestrator): add pattern AJV check to the example schema

workspaces/adoption-insights/packages/app/e2e-tests/insights.test.ts
This PR introduces the following improvements to the `Adoption Insights` Playwright end-to-end test suite:
* 🔍 **Replaced manual assertions** with `toMatchAriaSnapshot()` for:
* "Active users"
* "Total number of users"
* "Top 3 plugins"
* 🚀 **Reused `navigate()`** helper across all relevant tests for consistent navigation.
* 🧪 **Verified ARIA-level accessibility** for key panels and charts.
* 📄 **Added no-search-results validation** during the simulated user search interaction.
* 🔄 **Improved scrolling behavior** using `scrollIntoViewIfNeeded()` to handle dynamically rendered elements.
These changes ensure more **accessible UI testing**, improved **readability**, and better **test resilience** to layout shifts or timing issues. They also help surface accessibility regressions earlier by …
=> Enhance Adoption Insights E2E Tests with ARIA Snapshots and Improved Navigation

workspaces/lightspeed/.changeset/healthy-olives-rush.md, workspaces/lightspeed/plugins/lightspeed/src/components/LightSpeedChat.tsx, workspaces/lightspeed/plugins/lightspeed/src/components/__tests__/LightspeedChat.test.tsx, workspaces/lightspeed/plugins/lightspeed/src/const.ts
https://issues.redhat.com/browse/RHDHPAI-852
User will be now able to drag and drop the files in the chatbot message container.
**Screenshots:**
=> feat(lightspeed): support drag and drop in lightspeed

workspaces/orchestrator/docs/auth.md
Added missing part on workflow application.properties required setup to make the whole thing work.
Included more polishing.
=> docs(orchestrator): auth widget doc improvement

workspaces/orchestrator/.changeset/honest-parents-exercise.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveMultiSelect.tsx
Fixes: FLPATH-2404
----
After:
---
Before:
=> fix(orchestrator): fix alignment of ActiveMultiSelect's chips

workspaces/orchestrator/.changeset/strong-actors-bow.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx
resolve [FLPATH-2348](https://issues.redhat.com/browse/FLPATH-2384)
=> fix(orchestrator): capitalize Orchestrator in path

workspaces/orchestrator/.changeset/grumpy-houses-switch.md, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowRunsTabContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowsTable.tsx, workspaces/orchestrator/plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
resolve [FLPATH-2383](https://issues.redhat.com/browse/FLPATH-2383)
=> fix(orchestrator): fix search and filter for 'running' and 'failed'

workspaces/orchestrator/.changeset/fresh-gorillas-know.md, workspaces/orchestrator/docs/orchestratorFormWidgets.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/applySelector.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/SchemaUpdater.tsx
=> feat(orchestrator): add support for selectors in SchemaUpdater [Backport]

workspaces/orchestrator/plugins/orchestrator-backend/src/service/router.ts, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInputs.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowResult.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
=> fix(orchestrator): multiple visibility issues [backport]

workspaces/global-header/.changeset/tidy-hairs-brush.md, workspaces/global-header/packages/app/package.json, workspaces/global-header/packages/app/src/components/Root/Root.tsx, workspaces/global-header/plugins/global-header/config.d.ts, workspaces/global-header/plugins/global-header/package.json, workspaces/global-header/yarn.lock
=> fix(global-header): update config.d.ts, update theme

.github/renovate.json
Since BCP updates are handled as part of planned Backstage updates, I'm reworking the Renovate rule to:
* Include BCP scoped packages
* Disable any updates since we will never be approving them via Dashboard anyway
=> Update renovate config to disable Backstage updates

workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx
Minor UI update. This `minWidth` avoids dropdown menu width changes from toggling disable/enable.
Before:
After:
=> fix(marketplace): minor UI fix

workspaces/orchestrator/.changeset/dull-otters-learn.md, workspaces/orchestrator/docs/orchestratorFormWidgets.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.test.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.ts
=> feat(orchestrator): add support for primitive numeric and bool values

workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts
to match ADR and docs, changed auth headers to X-Authorization-<provider> from X-<provider>-Authorization
=> fix(orchestrator): changed auth headers to start with X-Authorization

workspaces/global-header/.changeset/neat-walls-lay.md, workspaces/global-header/plugins/global-header/config.d.ts, workspaces/global-header/plugins/global-header/src/components/CompanyLogo/CompanyLogo.tsx
=> fix(global-header): update width and image rendering CSS

workspaces/redhat-resource-optimization/docs/dynamic-plugin.md
**Jira:** [RHINENG-18953](https://issues.redhat.com/browse/RHINENG-18953)
chore: updated dyamic-plugin.md
=> chore: updated dyamic-plugin.md

workspaces/orchestrator/docs/Permissions.md, workspaces/orchestrator/docs/rbac-policy.csv
resolve [FLPATH-2435](https://issues.redhat.com/browse/FLPATH-2435)
=> fix(orchestrator): update permissions.md

workspaces/adoption-insights/.changeset/some-bananas-sell.md, workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.test.ts, workspaces/adoption-insights/plugins/adoption-insights-backend/src/database/partition.ts
fixes an issue I introduced in #1085 that would have occurred in the last month of the year.
=> fix: adoption insights - partition - last month error

workspaces/orchestrator/.changeset/silly-trainers-check.md, workspaces/orchestrator/plugins/orchestrator-form-react/src/utils/generateUiSchema.test.ts, workspaces/orchestrator/plugins/orchestrator-form-react/src/utils/generateUiSchema.ts
=> feat(orchestrator): add support ui:order in UI schema [Backport]

workspaces/marketplace/.changeset/green-planes-yawn.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginInstallContent.tsx, workspaces/marketplace/plugins/marketplace/src/pages/MarketplacePluginInstallPage.tsx
Resolves:
https://issues.redhat.com/browse/RHDHBUGS-1876
=> fix(extensions): fix install page title in prod env

workspaces/orchestrator/package.json, workspaces/orchestrator/scripts/export-to-rhdh-repo.js, workspaces/orchestrator/yarn.lock
resolve [FLPATH-2497](https://issues.redhat.com/browse/FLPATH-2497)
=> chore(orchestrator): Add interactive CLI to export-to-rhdh-repo script

workspaces/redhat-resource-optimization/docs/rbac.md
chore: updated RBAC.md to include details around ros.[CLUSTER_NAME].[Project_Name] permission
**jira:** [RHINENG-18631](https://issues.redhat.com/browse/RHINENG-18631)
=> chore: updated RBAC.md to include details around ros.[CLUSTER_NAME].[Project_Name] permission

workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/__tests__/VerificationCodeStep.test.tsx, workspaces/sandbox/plugins/sandbox/src/components/SandboxCatalog/__tests__/SandboxCatalogCard.test.tsx, workspaces/sandbox/plugins/sandbox/src/hooks/useProductURLs.ts
Update openshift url :
from <cluster>/add/ns/<namespace-dev> to <cluster>/k8s/cluster/projects/<namespace-dev> in Sandbox Dashboard
Jira: https://issues.redhat.com/browse/SANDBOX-1350
=> fix(sandbox): update openshift url

workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationModal.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/PhoneNumberStep.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/VerificationCodeStep.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/__tests__/PhoneNumberStep.test.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/PhoneVerificationSteps/__tests__/VerificationCodeStep.test.tsx, workspaces/sandbox/plugins/sandbox/src/components/Modals/__tests__/AccessCodeInputModal.test.tsx
Jira: https://issues.redhat.com/browse/SANDBOX-1364
Right now phone verification modal has Spain as default country. 
With those changes the default country is undefined and user has to select one:
=> fix(sandbox): unset default country in phone verification

workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePage.tsx
=> fix(orchestrator): resolve run again menu css issue

workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePage.tsx
backport https://github.com/redhat-developer/rhdh-plugins/pull/1192
=> fix(orchestrator): resolve run again menu css issue backport 1192

workspaces/quickstart/.changeset/stale-cats-spend.md, workspaces/quickstart/plugins/quickstart/src/components/QuickstartDrawerProvider.tsx
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1894
=> fix(quickstart): fix to set quickstart-open local-storage key to true on first visit

workspaces/bulk-import/.changeset/wicked-owls-compare.md, workspaces/bulk-import/plugins/bulk-import-backend/src/catalog/catalogHttpClient.ts
Fix `/repos` unable to create bulk-import catalog PR.
Fixes https://issues.redhat.com/browse/RHDHBUGS-1869
=> fix(bulk-import): fix /repos unable to create bulk-import catalog PR

workspaces/marketplace/.changeset/sixty-phones-wave.md, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/PluginInstallStatusProcessor.test.ts, workspaces/marketplace/plugins/catalog-backend-module-marketplace/src/processors/PluginInstallStatusProcessor.ts
Fix slow change of plugin install status.
Fixes https://issues.redhat.com/browse/RHDHBUGS-1886
Before
https://github.com/user-attachments/assets/2ed9ce41-d738-4fc9-98b4-dad4763161fc
After
https://github.com/user-attachments/assets/3d7b3d92-c714-4291-a915-578ff4a7375c
=> fix(extensions): fix slow change of plugin install status

workspaces/marketplace/.changeset/chilled-moons-speak.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.tsx
Fixes: https://issues.redhat.com/browse/RHDHBUGS-1891
=> fix(extensions): hide extensions alerts while the plugins are still loading

workspaces/bulk-import/.changeset/dry-humans-lay.md, workspaces/bulk-import/plugins/bulk-import-backend/src/catalog/catalogHttpClient.ts
Fixes edit PR failure: 'Couldn't create a PR due to insufficient permissions'
Fixes https://issues.redhat.com/browse/RHDHBUGS-1908
Tested in rhdh-local and on cluster.
https://github.com/user-attachments/assets/70e5c5f1-b29b-46ea-9c83-7216550d6700
=> fix(bulk-import): fix edit PR

workspaces/redhat-resource-optimization/docs/dynamic-plugin.md
updated dynamic-plugin.md with latest release info of 1.2.0 version
=> chore: updated dynamic-plugin.md with latest release info

workspaces/orchestrator/.changeset/hip-parrots-drive.md, workspaces/orchestrator/docs/orchestratorFormWidgets.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/constants.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.test.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/evaluateTemplate.ts, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/utils/useRequestInit.ts
=> fix(orchestrator): skip empty headers

workspaces/orchestrator/.changeset/angry-clocks-run.md, workspaces/orchestrator/plugins/orchestrator-common/report.api.md, workspaces/orchestrator/plugins/orchestrator-common/src/QueryParams.ts, workspaces/orchestrator/plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowResult.tsx
FLPATH-2493
https://issues.redhat.com/browse/FLPATH-2493
=> workflow rerun - all input is readonly

workspaces/marketplace/README.md, workspaces/marketplace/catalog-info.yaml, workspaces/marketplace/docs/catalog/index.md, workspaces/marketplace/docs/catalog/packages.md, workspaces/marketplace/docs/catalog/plugins.md, workspaces/marketplace/docs/index.md, workspaces/marketplace/mkdocs.yaml
Hi, this is a first version of an improved techdocs. I like to continue on this later. But though that I can push it maybe in this state already.
=> docs(extensions): update techdocs and catalog-info.yaml

workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.test.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-common/report.api.md, workspaces/orchestrator/plugins/orchestrator-common/src/types.ts
[backport ](https://github.com/redhat-developer/rhdh-plugins/pull/1263)
=> fix(orchestrator): filter deleted workflows from workflows table - backport

workspaces/orchestrator/.changeset/smooth-moles-repair.md, workspaces/orchestrator/entities/greet-with-new-component/skeleton/catalog-info.yaml, workspaces/orchestrator/entities/greet-with-new-component/yamlgreet_with_new_component.yaml, workspaces/orchestrator/plugins/orchestrator-backend/src/service/DataIndexService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/OrchestratorService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/SonataFlowService.ts, workspaces/orchestrator/plugins/orchestrator-backend/src/service/api/v2.ts, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/WorkflowsTable.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
resolve [FLPATH-2633](https://issues.redhat.com/browse/FLPATH-2633)
plus updating the template to prompt entity name
=> fix(orchestrator):filter last run in wotkflows tab by entity

workspaces/orchestrator/.changeset/twenty-fishes-count.md, workspaces/orchestrator/plugins/orchestrator-form-react/src/components/OrchestratorFormWrapper.tsx, workspaces/orchestrator/plugins/orchestrator-form-react/src/components/StepperObjectField.tsx, workspaces/orchestrator/plugins/orchestrator-form-react/src/utils/getSortedStepEntries.ts, workspaces/orchestrator/plugins/orchestrator-form-react/src/utils/useValidator.ts
=> fix(orchestrator): validation order with ui:order - backport

workspaces/orchestrator/.changeset/orange-lamps-flow.md, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/OrchestratorPage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowPage.tsx
=> fix(orchestrator):fix wrong color for selected tab [Backport]

workspaces/marketplace/.changeset/funny-trains-yawn.md, workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogContent.test.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplaceCatalogGrid.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginFilter.tsx
**Resolves:**
https://issues.redhat.com/browse/RHIDP-8303
=> feat(extensions): ux improvements on the catalog page

workspaces/redhat-resource-optimization/.changeset/yellow-poets-cross.md, workspaces/redhat-resource-optimization/packages/backend/package.json, workspaces/redhat-resource-optimization/plugins/redhat-resource-optimization-backend/package.json, workspaces/redhat-resource-optimization/plugins/redhat-resource-optimization-common/package.json
Fixes #1317
/cc @davidfestal @ydayagi @mareklibra @batzionb @PreetiW
=> fix(resource-optimization): fix #1317: updated the outdated repository reference

workspaces/orchestrator/.changeset/strong-readers-rule.md, workspaces/orchestrator/plugins/orchestrator/src/components/InfoDialog.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/OrchestratorPage/InputSchemaDialog.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/VariablesDialog.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePageContent.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/ui/JsonCodeBlock.tsx
resolve [FLPATH-2638](https://issues.redhat.com/browse/FLPATH-2638)
=> fix(orchestrator):UI enhancement

workspaces/marketplace/.changeset/plugin-sidebar-ux-improvements.md, workspaces/marketplace/plugins/marketplace/src/components/Badges.tsx, workspaces/marketplace/plugins/marketplace/src/components/Links.tsx, workspaces/marketplace/plugins/marketplace/src/components/Markdown.tsx, workspaces/marketplace/plugins/marketplace/src/components/MarketplacePluginContent.tsx
https://issues.redhat.com/browse/RHIDP-8302
----------
----Before----
---------
-----After------
--------
- Made verified and certified icons smaller for better visual hierarchy
- Added proper padding, bullet points, and spacing to the Highlights section
- Applied medium-weight text and proper padding to the About section title
- Styled Links section title consistently with About section
- Reduced size of external link icons and improved alignment
=> feat(extensions): plugin side drawer UX improvements

workspaces/orchestrator/.changeset/mean-cherries-yell.md, workspaces/orchestrator/plugins/orchestrator/package.json, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/ServerlessWorkflowEditor.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowPage/WorkflowDetailsTabContent.tsx, workspaces/orchestrator/yarn.lock
=> fix(orchestrator): use CodeSnippet instead of kie-tools editor [Backport]

workspaces/orchestrator/docs/extensibleForm.md, workspaces/orchestrator/plugins/orchestrator-form-react/README.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/README.md
resolve some README links issues
=> docs(orchestrator): fix broken links, and make in repo links relative

workspaces/scorecard/.changeset/polite-flies-peel.md, workspaces/scorecard/plugins/scorecard-backend-module-github/package.json, workspaces/scorecard/plugins/scorecard-backend-module-jira/package.json, workspaces/scorecard/plugins/scorecard-backend/package.json, workspaces/scorecard/plugins/scorecard-common/package.json, workspaces/scorecard/plugins/scorecard-node/package.json, workspaces/scorecard/plugins/scorecard/package.json
Description
- Removed private flag from scorecard plugins
Todo - Needs to merge this [PR](https://github.com/redhat-developer/rhdh-plugins/pull/1503) before merging this PR (DONE)
=> fix(scorecard): remove private flags from package.json

workspaces/theme/.changeset/flat-mugs-wink.md
To resolve build issues on the overlay repo, see https://github.com/redhat-developer/rhdh-plugin-export-overlays/pull/1497
I like re-publish all packages of the theme workspace together
=> fix(theme): release all themes and test packages together to resolve build issues

workspaces/orchestrator/.changeset/six-grapes-lay.md, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowInstancePage/WorkflowInstancePage.tsx, workspaces/orchestrator/plugins/orchestrator/src/components/WorkflowRunDetails.tsx
=> fix(orchestrator): Simplify Workflow Instance page header

workspaces/orchestrator/.changeset/two-balloons-happen.md, workspaces/orchestrator/plugins/orchestrator-form-widgets/src/widgets/ActiveDropdown.tsx
=> fix(orchestrator): Shorten ActiveDropdown list of options
